### ISSUE TITLE
preprocess_cmds for package is failing "No such file or directory"

### ISSUE THREAD

**Issue by tuaris** [devrandom/gitian-builder#102]
I'm trying to create a package for Berkly DB5, but the `preprocess_cmds` are failing with:

```
sed -i.old 's/__atomic_compare_exchange/__atomic_compare_exchange_db/' src/dbinc/atomic.h
sed: can't read src/dbinc/atomic.h: No such file or directory
make: *** [/home/ubuntu/build/bitcoin/depends/work/build/x86_64-apple-darwin11/bdb/5.3.28-ee2ad065658/.stamp_preprocessed] Error 2
make: Leaving directory `/home/ubuntu/build/bitcoin/depends'
```

For example lets say I want to build a Bitcoin wallet using DB5.3 instead of DB4.8.  I would modify the [bdb.mk](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/bdb.mk) package as so to use version 5.3.28:

```
$(package)_version=5.3.28
$(package)_download_path=http://download.oracle.com/berkeley-db
$(package)_file_name=db-$($(package)_version).NC.tar.gz
$(package)_sha256_hash=76a25560d9e52a198d37a31440fd07632b5f1f8f9f2b6d5438f4bc3e7c9013ef
```

DB 5.3's directory structure is slightly different than DB 4.8:

``` 
ls -l db-5.3.28.NC/src/dbinc/{atomic.h,win_db.h}
-rw-r--r-- 1 debian debian 6612 Sep  9  2013 db-5.3.28.NC/src/dbinc/atomic.h
-rw-r--r-- 1 debian debian 3831 Sep  9  2013 db-5.3.28.NC/src/dbinc/win_db.h
```

I adjust the `preprocess_cmds` as needed and add an additional replacement for Windows:

```
define $(package)_preprocess_cmds
	sed -i.old 's/__atomic_compare_exchange/__atomic_compare_exchange_db/' src/dbinc/atomic.h
	sed -i.old 's/WinIoCtl\.h/winioctl\.h/g' src/dbinc/win_db.h
endef
```

What is wrong?

**Comment by tuaris** [comment]
Resolved by doing this:

```
define $(package)_preprocess_cmds
	sed -i.old 's/__atomic_compare_exchange/__atomic_compare_exchange_db/' src/dbinc/atomic.h && \
	sed -i.old 's/WinIoCtl.h/winioctl.h/' src/dbinc/win_db.h
endef
```

Apparently it needs to be a *single* command.

**Comment by devrandom** [comment]
This should be reported at the repository where the gitian descriptor lives, which is the bitcoin repository.  It's not gitian-project specific, but is a bug in the build process in the descriptor.

**Comment by mxaddict** [comment]
> Resolved by doing this:
> 
> ```
> define $(package)_preprocess_cmds
>     sed -i.old 's/__atomic_compare_exchange/__atomic_compare_exchange_db/' src/dbinc/atomic.h && \
>     sed -i.old 's/WinIoCtl.h/winioctl.h/' src/dbinc/win_db.h
> endef
> ```
> 
> Apparently it needs to be a _single_ one line command.

This helped :smile:
