### ISSUE TITLE
make-base-vm using 404'd ubuntu URL

### ISSUE THREAD

**Issue by danwxyz** [devrandom/gitian-builder#127]
When using `make-base-vm` I encounter this error:

`E: Failed getting release file http://127.0.0.1:3142/archive.ubuntu.com/ubuntu/dists/lucid/Release`

Upon further inspection, http://archive.ubuntu.com/ubuntu/dists/lucid/Release returns `404 Not Found`.

**Comment by josephbisch** [comment]
Lucid has reached eol over a year ago, even for the server version. Are any projects that use Gitian even using Lucid anymore? Maybe the default should be updated to something more recent than Lucid?

If you really need to use Lucid, the correct URL would be `http://old-releases.ubuntu.com/ubuntu/dists/lucid/Release`. There is a [blog post](http://fridge.ubuntu.com/2015/04/30/ubuntu-10-04-lucid-lynx-end-of-life-reached-on-april-30-2015/) about the eol status.

**Comment by danwxyz** [comment]
I should have clarified. Lucid seems to be the default.

**Comment by josephbisch** [comment]
Yes, so you can use `--suite` to specify a different Ubuntu suite. If you are trying to build a software project that already makes use of Gitian, then you should use whatever suite that project uses, based on the contents of the Gitian descriptors.

**Comment by danwxyz** [comment]
Ah I see. I am attempting to build Bitcoin and in its documentation it supplies the `--suite` flag. Thanks!

**Comment by TTcoinDeveloper** [comment]
Just install ---> (apt-get install -y apt-cacher-ng) and make sure it is running (service apt-cacher-ng start) and you should be good.
