### ISSUE TITLE
lxc fails to start

### ISSUE THREAD

**Issue by achow101** [devrandom/gitian-builder#128]
When attempting to do a build of bitcoin with lxc, lxc fails to start. It has the following error

```
init.lxc: failed to mount /dev/shm : No such file or directory
sudo: unknown user: ubuntu
sudo: unable to initialize policy plugin
```

The OS is Ubuntu 16.04

**Comment by josephbisch** [comment]
You can get more verbose information from lxc, but it looks like the sudo errors are coming from the inside the container.

The file [bootstrap-fixup.in](https://github.com/devrandom/gitian-builder/blob/master/target-bin/bootstrap-fixup.in) has `|| true` at the end of the adduser command to prevent the fixup script from failing if there is already an ubuntu user in the container.

I guess the problem in this case is that there must have been some issue with the adduser command other than an ubuntu user already existing. But the `|| true` makes the script continue no matter what. Maybe see what errors you get if you remove the `|| true`? When you run gbuild again it should invoke make-clean-vm, which should run bootstrap-fixup again.

**Comment by josephbisch** [comment]
I saw your corresponding bug under the lxc/lxc repo. I saw the messages "mount failed with error: Invalid argument". Is it possible you are using LVM on the host?

**Comment by unsystemizer** [comment]
The error doesn't state that LXC failed to start

**Comment by jonasschnelli** [comment]
Have the same issue after upgrading my host from Debian 8 to Debian 9
