### ISSUE TITLE
Allow to use debootstrap from other location

### ISSUE THREAD

**Issue by tigusoft** [devrandom/gitian-builder#129]
E.g. on Debian Jessie you can use Gitian with Xenial and everything works if only you only provide the script template for Xenial.

This can be done by manually digging in /usr/share/... but if you do not want to change system wide program files like that - then other option would be to locally (in temp dir) create copy of that and add in the missing template for systems like Xenial, then export env DEBOOTSTRAP_DIR pointing to it.

This plan is blocked by make-base-vm clearing env and not exporting the above.

Env should preserve this env variable.

**Comment by josephbisch** [comment]
So are you saying that debootstrap doesn't recognize the xenial template in `/usr/share/debootstrap/scripts/`? Do you have an error message from when you try running Gitian?

The debootstrap package in Debian Jessie doesn't include a script for xenial, but the package in jessie-backports does include the script for xenial. So are you using the jessie-backports version of debootstrap? Running `apt-cache policy debootstrap` should give you that information.

If the template isn't being recognized in the default location, but it is being recognized when you use a custom directory, then that seems like it may be a debootstrap bug.

**Comment by tigusoft** [comment]
@josephbisch It would recognize it there, yes. 

But we wanted to allow also users who do not wish to use any not default repositories nor to change system wide /usr/ manually to use custom templates.

I written a small patch that passes env DEBOOSTRAP_DIR and this allows to do above.

**Comment by devrandom** [comment]
Thank you.
