### ISSUE TITLE
Gitian Key

### ISSUE THREAD

**Issue by terrylai** [devrandom/gitian-builder#131]
Hello,

I want to build bitcoin V 0.13.0 using gitian builder. But in the document I find one parameter which is named as "Gitian key". I want to know how to make it or find it?

The doc content is something like in the following:

 pushd ./bitcoin
 export SIGNER=(your Gitian key, ie bluematt, sipa, etc)
 export VERSION=0.13.0
 git fetch
 git checkout v${VERSION}
 popd

Thanks!

**Comment by MarcoFalke** [comment]
It is just your pgp key. Keep in mind you only need this for the signing step and not building.

**Comment by devrandom** [comment]
If the docs are unclear, a PR improving them would be appreciated.
