### ISSUE TITLE
Can't pass sanity test or other build on Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by unsystemizer** [devrandom/gitian-builder#139]
* OS: Ubuntu 16.04 x64
* VMBuilder: vm-builder_0.12.4+bzr494.orig.tar.gz
* gitian-builder cloned from github master, using the KVM approach

I run this: `$ sudo bin/make-base-vm --arch i386`

I get this:

```
Processing triggers for libc-bin (2.23-0ubuntu4) ...
Errors were encountered while processing:
 sudo
Extracting templates from packages: 100%
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I also tried this: `sudo bin/make-base-vm --arch amd64 --suite trusty`
And then towards the end I got this:
```
invoke-rc.d: policy-rc.d denied execution of restart.
Configuration file '/etc/sudoers'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 EOF on stdin at conffile prompt
Errors were encountered while processing:
 sudo
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Edit: I tried one more time and it seems this new sudo package (update?) has a problem with previous changes.

```
2016-11-06 05:48 DEBUG   : Setting up libgnutls-openssl27:amd64 (3.4.10-4ubuntu1.1) ...
2016-11-06 05:48 DEBUG   : Setting up sudo (1.8.16-0ubuntu1.2) ...
2016-11-06 05:48 DEBUG   :
2016-11-06 05:48 DEBUG   : Configuration file '/etc/sudoers'
2016-11-06 05:48 DEBUG   :  ==> Modified (by you or by a script) since installation.
2016-11-06 05:48 DEBUG   :  ==> Package distributor has shipped an updated version.
2016-11-06 05:48 DEBUG   :    What would you like to do about it ?  Your options are:
2016-11-06 05:48 DEBUG   :     Y or I  : install the package maintainer's version
2016-11-06 05:48 DEBUG   :     N or O  : keep your currently-installed version
2016-11-06 05:48 DEBUG   :       D     : show the differences between the versions
2016-11-06 05:48 DEBUG   :       Z     : start a shell to examine the situation
2016-11-06 05:48 DEBUG   :  The default action is to keep your current version.
2016-11-06 05:48 DEBUG   : *** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
2016-11-06 05:48 DEBUG   :  end of file on stdin at conffile prompt
2016-11-06 05:48 DEBUG   : Setting up vim-common (2:7.4.1689-3ubuntu1.1) ...
```

**Comment by EvgenijM86** [comment]
I encountered the same problem.

**Comment by flintsoft** [comment]
I had the same problem on a fresh Ubuntu 16.04 LTS. The solution I found from another post is:

1.: Change the word 'dist-upgrade' to 'update' in:
     /usr/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/dapper.py
2.: Delete /usr/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/dapper.pyc

That solution fixed the problem, <code>make-base-vm</code> now compiles smoothly.
 
Quote:
'Annoying that the "solution" to a problem like this is to edit the installed package, but that's what it is.'

Found here:
[http://askubuntu.com/questions/852814/dpkg-error-processing-package-sudo-configure](url)

**Comment by unsystemizer** [comment]
Thanks @flintsoft 
I saw this link elsewhere the other day and was thinking to revisit this bug when I find time. 
Great to know that it works. I hope to give it a try and close this later this week.

**Comment by unsystemizer** [comment]
I thought that was the same workaround as [this](https://www.reddit.com/r/Bitcoin_Classic/duplicates/5ms06k/im_having_trouble_replicating_gitian_build/) one, but it's slightly different. I don't know which is correct (both?).
I tried @flintsoft's workaround and was able to build a Trusty VM. 

I'm leaving this open in case the maintainer or somebody else wants to create a PR to fix this.

**Comment by josephbisch** [comment]
@unsystemizer @flintsoft Thanks for looking into this.

It seems to me that the `--option=Dpkg::Options::=--force-confnew` seems like a better option. If you change dist-upgrade to update, then you are not actually upgrading the packages, because `apt-get update` will download package information, but not install any packages like other commands such as `apt-get dist-upgrade` will. It seems like it would be a good idea for everyone to try to be on the same page with regard to running the latest packages within their Gitian VM.

Ultimately, this is a VMBuilder bug, so it can't be fixed in gitian-builder directly. [Here is the VMBuilder bug](https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1618899). As you can see there, they plan to drop the vm-builder package from Ubuntu Zesty. It sounds like they intend to add it back when it is in a usable state again, but who knows what will end up happening. It might be a good idea to consider gitian-builder's future if development of VMBuilder is abandoned.
