### ISSUE TITLE
Watch newroco vmbuilder fork

### ISSUE THREAD

**Issue by josephbisch** [devrandom/gitian-builder#143]
There is a fork of VMBuilder at https://github.com/newroco/vmbuilder. We should watch it. It would be nice if the changes get integrated back upstream into VMBuilder, but we may want to consider switching to the fork if upstream development and fixes remain stagnant and if this fork seems to be actively developed. It looks to me like the last commit upstream was in 2015.

As was discussed in #139, upstream VMBuilder appears to currently be broken and requires manual editing of the Python source to not error out (though it doesn't look like the VMBuilder fork has fixed that issue yet either).

What are people's thoughts on this?

**Comment by devrandom** [comment]
I'll defer to you on this.

**Comment by josephbisch** [comment]
As an update on this:

It sounds to me from [this comment](https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1260062/comments/15) that the newroco fork is now considered the new vmbuilder upstream. It seems that there is hope for vmbuilder to remain in the repos for the new Ubuntu release (artful).

I've also seen a number of vmbuilder bug reports mention [uvtool](https://help.ubuntu.com/lts/serverguide/cloud-images-and-uvtool.html) as a maintained alternative, so we can also look at that and see if it meets our needs.
