### ISSUE TITLE
ubuntu 14

### ISSUE THREAD

**Issue by mraksoll** [devrandom/gitian-builder#146]
this trash not work 

builder@ubuntu:~/gitian-builder$ start-target 32 lucid-i386
/home/builder/gitian-builder/libexec/start-target: 26: /home/builder/gitian-builder/libexec/start-target: cannot create var/target.pid: Permission denied
/home/builder/gitian-builder/libexec/start-target: 25: /home/builder/gitian-builder/libexec/start-target: cannot create var/target.log: Permission denied

**Comment by unsystemizer** [comment]
Permission denied? Fake bug alert!
