### ISSUE TITLE
sudo bin/gbuild --commit learncoin=HEAD ../learncoin/contrib/gitian-descriptors/gitian-win32.yml not found repository

### ISSUE THREAD

**Issue by hamundnic** [devrandom/gitian-builder#156]
Hello recently  i was trying to buit it gitian-win32.yml and give me this error 👍 
`sudo bin/gbuild --commit learncoin=HEAD ../learncoin/contrib/gitian-descriptors/gitian-win32.yml

remote: Repository not found.
fatal: repository 'https://github.com/sheetgold-project/sheetgold.git/' not found
bin/gbuild:21:in `system!': failed to run cd inputs/sheetgold && git fetch --update-head-ok https://github.com/sheetgold-project/sheetgold.git +refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (RuntimeError)
    from bin/gbuild:268:in `block in <main>'
    from bin/gbuild:256:in `each'
    from bin/gbuild:256:in `<main>'
`

**Comment by josephbisch** [comment]
There is no such account on github by the name sheetgold-project (see: https://github.com/sheetgold-project/). Maybe it existed at one point, but they may have deleted their account. If you are trying to build learncoin, you should point gbuild at whatever the URL is for learncoin.

**Comment by hamundnic** [comment]
thank you for answer me , i am trying to make bin/gbuild --commit
sheetgold=HEAD ../sheetgold/contrib/gitian-descriptors/gitian-win32.yml
and then github say me :

remote: Repository not found.
fatal: repository 'https://github.com/sheetgold-project/sheetgold.git/' not
found
bin/gbuild:21:in `system!': failed to run cd inputs/sheetgold && git fetch
--update-head-ok https://github.com/sheetgold-project/sheetgold.git
+refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (RuntimeError)
    from bin/gbuild:268:in `block in <main>'
    from bin/gbuild:256:in `each'
    from bin/gbuild:256:in `<main>'


but i have the origin with http://github.com/hamundnic/sheetgold.git

all the step was successfull except build gitian-win23.yml

please i need that for finish if you can help me i will be happy with you.

thank you

2017-10-01 13:13 GMT+02:00 Joseph Bisch <notifications@github.com>:

**Comment by josephbisch** [comment]
You can use --url sheetgold=http://github.com/hamundnic/sheetgold.git to specify the correct URL.

**Comment by hamundnic** [comment]
thank you i was trying with that ad not found but i could make it
,creatting a organization sheetgold-project. one more time thank you.

2017-10-02 2:55 GMT+02:00 Joseph Bisch <notifications@github.com>:

**Comment by devrandom** [comment]
This is very likely to be a bug in the project specific build script, and is not a gitian bug, so closing.
