### ISSUE TITLE
Mismatched hash results

### ISSUE THREAD

**Issue by InTheAbsenseOfDemocracyThereIsCommunism** [devrandom/gitian-builder#160]
When trying to compile deps, I get an issue with the sha256 hash result of miniupnpc-1.9.20140401.tar.gz. Is there any way to change what will be put into the build-script in var to match the file that I have, as I am unable to find the file with a matching hash.

**Comment by josephbisch** [comment]
Hi,

Please post a link to the project you are trying to build. The miniupnpc-1.9.20140401.tar.gz sounds like a rather old version of miniupnpc. More likely than not, this sounds like an issue with the Gitian descriptor for the project you are trying to build rather than an issue with gitian-builder itself.

**Comment by InTheAbsenseOfDemocracyThereIsCommunism** [comment]
You'd be correct, it is fairly old. I am trying to clone a fairly old version of litecoin and more or less make my own coin (just for fun haha), but the guide I am following recommends to use litecoin version 0.8.7.4(https://github.com/litecoin-project/litecoin/releases/tag/v0.8.7.4). Although, you're right. As I think about it this is more so an issue with the project I am trying to compile than the builder..

**Comment by josephbisch** [comment]
I got that version of miniupnpc from http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.9.20140401.tar.gz and it matches the sha256sum from https://github.com/litecoin-project/litecoin/blob/c1e46ab3a90bd90b9092761214e841b165d4dbc8/contrib/gitian-descriptors/gitian.yml which is the Gitian descriptor from that version of litecoin.

**Comment by devrandom** [comment]
the build script comes from the yaml file, which is provided by the user, so should be easy to change.  I assume though that OP's issue was resolved.
