### ISSUE TITLE
Error During Build Phase

### ISSUE THREAD

**Issue by neutcoin-project** [devrandom/gitian-builder#161]
So I've had an error building an altcoin using Gitian. Everything goes smooth, all dependencies are built without any errors, but when I go to build for Win32, I get 
`failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)` 
after Gitian is running the build script.

Possibly important details:
Building with KVM (I have checked and I do have support)
Building on Ubuntu 16.04.3 LTS
arch: amd64, suite: precise
Compiled with: 
`sudo bin/gbuild --commit neutcoin=HEAD ./neutcoin/contrib/gitian-descriptors/gitian-win32.yml`
Coin forked from Litecoin v0.8.7.4 (I will experiment with other versions)
If there's anything missing I'll add

I've also included exactly what the terminal says and what build.log says. If anything's missing please let me know, I've been trying to compile for a week now and I've tried everything I could see on the internet.
[errors.txt](https://github.com/devrandom/gitian-builder/files/1596433/errors.txt)
(If using Windows, open with a text editor that supports Unix line endings or else it's difficult to read)

Thanks in advance!

**Comment by josephbisch** [comment]
Seems to just be an issue with building the project, not with Gitian itself.

Looks like it all stems from the files in this directory being prefixed with icons\ - https://github.com/neutcoin-project/neutcoin/tree/master/src/qt/res/icons.

Hope that helps. You can close this issue.

**Comment by neutcoin-project** [comment]
I've tried removing the prefix, actually with the setup I had there wasn't the prefix. I tried running with and without prefixes and at the end of the build log it still says "i686-w64-mingw32-windres: can't open icon file `icons/bitcoin.ico': No such file or directory". I tried running a grep scan for instances of icons/bitcoin.ico and I found two files with this link. I will try and troubleshoot and see if I can get it working.

**Comment by lemanum** [comment]
HI
I have another error maybe you can help me
all dependencie are built with no problem but wen i try to build the gitian-win32.yml i get this error

**bin/gbuild:21:in `system!': failed to run on-target setarch i386 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)**
	from bin/gbuild:149:in `build_one_configuration'
	from bin/gbuild:285:in `block (2 levels) in <main>'
	from bin/gbuild:280:in `each'
	from bin/gbuild:280:in `block in <main>'
	from bin/gbuild:278:in `each'
	from bin/gbuild:278:in `<main>'

**And on Build log we can see** 

i586-mingw32msvc-g++ -c -frandom-seed=lemanum -O2 -frtti -fexceptions -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -DBOOST_THREAD_USE_LIB -DENABLE_WALLET -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_QRCODE -DUSE_UPNP=1 -DMINIUPNP_STATICLIB -DSTATICLIB -DBITCOIN_NEED_QT_PLUGINS -DHAVE_BUILD_INFO -DWIN32 -D_MT -DBOOST_THREAD_PROVIDES_GENERIC_SHARED_MUTEX_ON_WIN -DQT_THREAD_SUPPORT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I'../../qt/include/QtCore' -I'../../qt/include/QtNetwork' -I'../../qt/include/QtGui' -I'../../qt/include' -I'../../build' -I'src' -I'src/json' -I'src/qt' -I'../../build' -I'src/leveldb/include' -I'src/leveldb/helpers' -I'../boost_1_47_0' -I'../db-4.8.30.NC/build_unix' -I'../openssl-1.0.1b/include' -I'../qrencode-3.2.0' -I'../../qt/include/ActiveQt' -I'build' -I'build' -I'../../qt/mkspecs/unsupported/win32-g++-cross' -o build/txdb-leveldb.o src/txdb-leveldb.cpp
cc1plus: error: unrecognized command line option "-Wno-ignored-qualifiers"
make[1]: *** [build/txdb-leveldb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/ubuntu/build/lemanum'
make: *** [release] Error 2

If somebody can take little time to explain me?? 

[Error gitian win.txt](https://github.com/devrandom/gitian-builder/files/1609691/Error.gitian.win.txt)

**Comment by Coinzo** [comment]
HI 
Maybe you can help me
i built all dependencie without anny problem but i get error for built the gitian-win32.yml 

Running build script (log in var/build.log)
bin/gbuild:21:in `system!': failed to run on-target setarch i386 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
	from bin/gbuild:149:in `build_one_configuration'
	from bin/gbuild:285:in `block (2 levels) in <main>'
	from bin/gbuild:280:in `each'
	from bin/gbuild:280:in `block in <main>'
	from bin/gbuild:278:in `each'
	from bin/gbuild:278:in `<main>'


**Build log show**

DQT_NETWORK_LIB -DQT_CORE_LIB -I'../../qt/include/QtCore' -I'../../qt/include/QtNetwork' -I'../../qt/include/QtGui' -I'../../qt/include' -I'../../build' -I'src' -I'src/json' -I'src/qt' -I'../../build' -I'src/leveldb/include' -I'src/leveldb/helpers' -I'../boost_1_47_0' -I'../db-4.8.30.NC/build_unix' -I'../openssl-1.0.1b/include' -I'../qrencode-3.2.0' -I'../../qt/include/ActiveQt' -I'build' -I'build' -I'../../qt/mkspecs/unsupported/win32-g++-cross' -o build/txdb-leveldb.o src/txdb-leveldb.cpp
cc1plus: error: unrecognized command line option "-Wno-ignored-qualifiers"
make[1]: *** [build/txdb-leveldb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/ubuntu/build/lemanum'
make: *** [release] Error 2

Can somebody help me? its for build lemanum windows wallet..

**Comment by neutcoin-project** [comment]
Edit:
I've been tweaking the descriptor slightly to no avail. Here's what I had before tweaks:
[https://github.com/neutcoin-project/neutcoin/blob/master/contrib/gitian-descriptors/gitian-win32.yml](url)
Maybe it's not the icon names but an error in the descriptor? I've been parsing through the descriptor but can't seem to find any potential problems.

**Comment by Mathiew1** [comment]
what did you do

**Comment by Mathiew1** [comment]
why did you closed the issue did you fixed it
