### ISSUE TITLE
cc1plus: error: unrecognized command line option "-Wno-ignored-qualifiers"

### ISSUE THREAD

**Issue by Coinzo** [devrandom/gitian-builder#162]
**Hello 
I try to build lemanum windows wallet with Gitian-builder
All dependencies are create without any problem**

sudo bin/gbuild ../LMN/contrib/gitian-descriptors/gitian-win32.yml

**i get this error: (show in build/log)**

i586-mingw32msvc-g++ -c -frandom-seed=lemanum -O2 -frtti -fexceptions -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -DBOOST_THREAD_USE_LIB -DENABLE_WALLET -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_QRCODE -DUSE_UPNP=1 -DMINIUPNP_STATICLIB -DSTATICLIB -DBITCOIN_NEED_QT_PLUGINS -DHAVE_BUILD_INFO -DWIN32 -D_MT -DBOOST_THREAD_PROVIDES_GENERIC_SHARED_MUTEX_ON_WIN -DQT_THREAD_SUPPORT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I'../../qt/include/QtCore' -I'../../qt/include/QtNetwork' -I'../../qt/include/QtGui' -I'../../qt/include' -I'../../build' -I'src' -I'src/json' -I'src/qt' -I'../../build' -I'src/leveldb/include' -I'src/leveldb/helpers' -I'../boost_1_47_0' -I'../db-4.8.30.NC/build_unix' -I'../openssl-1.0.1b/include' -I'../qrencode-3.2.0' -I'../../qt/include/ActiveQt' -I'build' -I'build' -I'../../qt/mkspecs/unsupported/win32-g++-cross' -o build/txdb-leveldb.o src/txdb-leveldb.cpp
cc1plus: error: unrecognized command line option "-Wno-ignored-qualifiers"
make[1]: *** [build/txdb-leveldb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/ubuntu/build/lemanum'
make: *** [release] Error 2

[Error gitian win.txt](https://github.com/devrandom/gitian-builder/files/1610090/Error.gitian.win.txt)

**Any idea how to solve it?**

**Comment by josephbisch** [comment]
Based on the descriptor in the Lemanum repository I found (https://github.com/lemanum/LMN/blob/master/contrib/gitian-descriptors/gitian-win32.yml), it seems like it uses Ubuntu Lucid for the build VM/container.

Since this version of Ubuntu has been eol since 2013, I recommend that you change the Gitian descriptors to use a current version of Ubuntu, if you have any relation to the Lemanum project.

In any case, it seems like an issue with the descriptor rather than Gitian itself.

**Comment by unikaq** [comment]
Hi joseph
Same problem for me,
Coins did you manage?
how to update the gitian descriptor? why the dependencie built without problem with Lucid   arch I386?

Need help pleasse

**Comment by ivan-cbqa** [comment]
same issue :(

**Comment by josephbisch** [comment]
As was stated, this appears to be an issue with the descriptors in the individual projects, rather than an issue with Gitian itself.

Please raise the issue of the bugs in the descriptors with the individual projects.
