### ISSUE TITLE
Boost No such file or directory but extract was OK in Staging Include

### ISSUE THREAD

**Issue by unikaq** [devrandom/gitian-builder#164]
Hello I don't understand, 
All the extraction was in staging so why I get this errors?

+ make -f makefile.linux-mingw -j2 DEPSDIR=/home/ubuntu/staging lemanumd.exe USE_UPNP=0 DEBUGFLAGS=-frandom-seed=lemanum USE_SSE2=1
g++ -c  -o obj/alert.o alert.cpp
/bin/sh ../share/genbuild.sh obj/build.h
In file included from alert.h:9:0,
                 from alert.cpp:5:
serialize.h:18:48: fatal error: boost/type_traits/is_fundamental.hpp: No such file or directory

Here my build files
[build-2.log](https://github.com/devrandom/gitian-builder/files/1649693/build-2.log)

Thank you for help

**Comment by devrandom** [comment]
apologies, but it is too time consuming to debug specific build scripts.  perhaps add some debugging output or use `on-target` to debug.
