### ISSUE TITLE
failed to run make-clean-vm --suite lucid --arch i386 (RuntimeError)

### ISSUE THREAD

**Issue by blockchaintrainer** [devrandom/gitian-builder#173]
I am getting below error while compiling gitian.yml
qemu-img: target-lucid-i386.qcow2: Could not open 'base-lucid-i386.qcow2': No such file or directory
bin/gbuild:21:in `system!': failed to run make-clean-vm --suite lucid --arch i386 (RuntimeError)
	from bin/gbuild:57:in `build_one_configuration'
	from bin/gbuild:300:in `block (2 levels) in <main>'
	from bin/gbuild:295:in `each'
	from bin/gbuild:295:in `block in <main>'
	from bin/gbuild:293:in `each'
	from bin/gbuild:293:in `<main>'

Is there any solution for this?

**Comment by StarNeit** [comment]
I am getting similar issue when I run `make-clean-vm` in debian.

./bin/make-base-vm -—lxc
make-clean-vm —suite xenial —arch amd64

lxc-execute: start.c: lxc_spawn: 1079 Failed to find gateway addresses. lxc-execute: start.c: __lxc_start: 1346 Failed to spawn container “gitian”.

I am facing this gateway address error when I run make-clean-vm command in debian linux.
I thought it was bridge connection issue, but no luck so far.
@blockchaintrainer , have you solve your issue?

**Comment by blockchaintrainer** [comment]
I changed the suites and architectures in the Gitian.yml and this fixed the issue.

suites:
- "precise"
architectures:
- "amd64"

**Comment by StarNeit** [comment]
I still have "Failed to find gateway addresses" error now.

would you please let me know which guide did you follow when you do gitian build, @blockchaintrainer ?

I am trying for over 7 days to build with gitian, but still no luck.

Thank you.

**Comment by blockchaintrainer** [comment]
I followed two guides mainly - Learncoin Video on youtube and the below website. Both are useful but still you will get errors even though you follow these guides accurately. You need to make few changes in the Gitian file so as to match your virtual machine configuration. I made these few changes and my windows wallet was created successfully.

Most importantly make sure to check the files in your script and in the inputs folder are matching with each other.
https://coinaxis.com/index.php/tutorials/entry/how-to-do-a-gitian-build-for-litecoin-tutorial-coinaxis

**Comment by devrandom** [comment]
Sounds like the issue was with the script, so closing this.

**Comment by devrandom** [comment]
By the way, there's #gitian on Freenode IRC if you want to communicate in real time.
