### ISSUE TITLE
Issue: Failed to find gateway addresses when run `make-clean-vm`

### ISSUE THREAD

**Issue by StarNeit** [devrandom/gitian-builder#175]
./bin/make-base-vm -—lxc
make-clean-vm —suite xenial —arch amd64

`lxc-execute: start.c: lxc_spawn: 1079 Failed to find gateway addresses.
lxc-execute: start.c: __lxc_start: 1346 Failed to spawn container “gitian”.`

I am facing this gateway address error when I run `make-clean-vm` command in debian linux.
I thought it was bridge connection issue, but no luck so far.
Any comment or response would be helpful, thank you.

**Comment by devrandom** [comment]
What version is your Debian version?

**Comment by TFTcoin** [comment]
Debian 8.4 :)

**Comment by achow101** [comment]
Use `ifconfig` and see if you have a `br0` or a `lxcbr0` device. You probably have a `lxcbr0` device, in which case you will need to do `export LXC_BRIDGE=lxcbr0`. You will then have to run `sudo ifconfig lxcbr0 up 10.0.2.2`.

If you see `br0`, you probably need to run `sudo ifconfig br0 up 10.0.2.2`.

**Comment by TTcoinDeveloper** [comment]
apt install lxc libvirt-clients debootstrap
and then proper linking of boost-mingw-gas-cross patch

**Comment by devrandom** [comment]
closing since no followup from OP
