### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by CNOJAME** [devrandom/gitian-builder#183]
Current Path for running script:

root@ubuntu:/home/cno# ls -lrt
drwxrwxr-x  7 cno cno     4096 May 27 15:48 widecash
drwxr-xr-x 14 cno cno     4096 May 30 06:05 gitian-builder

Error:

Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
   from ./bin/gbuild:163:in `build_one_configuration'
   from ./bin/gbuild:300:in `block (2 levels) in <main>'
   from ./bin/gbuild:295:in `each'
   from ./bin/gbuild:295:in `block in <main>'
   from ./bin/gbuild:293:in `each'
   from ./bin/gbuild:293:in `<main>'
root@ubuntu:/home/cno/gitian-builder# 

build.log

libtool: install: /usr/bin/install -c qrencode /home/ubuntu/install/bin/qrencode
make[2]: Leaving directory `/home/ubuntu/build/qrencode-4.0.0'
make[1]: Leaving directory `/home/ubuntu/build/qrencode-4.0.0'
+ cd ..
+ cd widecash
bash: line 30: cd: widecash: No such file or directory

Pls help to how to fix right directory ?

**Comment by TFTcoin** [comment]
The same error, how to fix that, home user id debian, but script show ubuntu.

**Comment by devrandom** [comment]
This is very likely to be a bug in the project specific build script, and is not a gitian bug.
