### ISSUE TITLE
onfig

### ISSUE THREAD

**Issue by cryptofarm777** [devrandom/gitian-builder#193]

**Comment by silence48** [comment]
??

**Comment by datacoin2017** [comment]
??

**Comment by devrandom** [comment]
!!

**Comment by cryptofarm777** [comment]
My apologies, this was a typo. I was having Garbage input compile errors
with mac-qmake.conf file.

**Comment by silence48** [comment]
No problem  did you get it figured out

**Comment by cryptofarm777** [comment]
I passed the the .conf file by up emptying the file. I kept getting garbage
input patch errors. Still have not diagnosed what the cause was. I was able
to pass the compile error onto other errors which i am diagnosing
currently. Again, sorry for the typo on this beginning thread. I have been
compiling dash/ sparks reborn src files, rebranding.
