### ISSUE TITLE
tar: Error is not recoverable: exiting now

### ISSUE THREAD

**Issue by cryptofarm777** [devrandom/gitian-builder#194]
Hi there, having more compiling issues. Perhaps some advice could help please. During the last part of compiling during make, i get the below error where it fails. 

++ echo 'opioidrxcore-*.tar.gz'
+ SOURCEDIST='opioidrxcore-*.tar.gz'
++ sed 's/.tar.*//'
++ echo 'opioidrxcore-*.tar.gz'
+ DISTNAME='opioidrxcore-*'
+ mkdir -p temp
+ pushd temp
~/build/OpioidRX/temp ~/build/OpioidRX
+ tar xf '../opioidrxcore-*.tar.gz'
tar: ../opioidrxcore-*.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

**Comment by devrandom** [comment]
This looks like an issue for the specific project using gitian, rather than gitian itself

**Comment by Prometeus1998** [comment]
unsubscribe thanks！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Dev&amp;nbsp;Random&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月30日(星期天) 晚上7:52
收件人:&nbsp;&quot;devrandom/gitian-builder&quot;<gitian-builder@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [devrandom/gitian-builder] tar: Error is not recoverable: exiting now (#194)
