### ISSUE TITLE
Failed to setup gitian building image trusty

### ISSUE THREAD

**Issue by josephnicholas** [devrandom/gitian-builder#198]
OS: Ubuntu 16.04
LXC enabled

Hello @devrandom,

I have an issue where it just happened when I restarted my VPS. Everything was working great until after restarted and ran a build again, using the `make-base-vm --lxc --arch amd64 --suite trusty` I got this error.

```I: Retrieving InRelease 
I: Failed to retrieve InRelease
I: Retrieving Release 
E: Failed getting release file http://127.0.0.1:3142/archive.ubuntu.com/ubuntu/dists/trusty/Release
```

It seems like its pointing to my localhost which is wrong, since I didn't do anything before I restarted. Please help.

**Comment by josephbisch** [comment]
Looks like maybe the apt-cacher-ng service was running before you restarted the VPS and then you didn't start it after the restart.

If you want apt-cacher-ng to automatically start:
```
sudo systemctl enable apt-cacher-ng
```

If you want to manually start apt-cacher-ng (needs to be run once per boot every time you intend to use apt-cacher-ng):
```
sudo systemctl start apt-cacher-ng
```

**Comment by moonroomcash** [comment]
debian@dibyajit:~/gitian-builder$ bin/make-base-vm --lxc --arch amd64 --suite jessie
[sudo] password for debian:
I: Retrieving Release
E: Failed getting release file http://127.0.0.1:3142/archive.ubuntu.com/ubuntu/dists/jessie/Release
i can't create jeesie image 
@devrandom plaese help me

**Comment by josephnicholas** [comment]
Closing this issue, since this was already fixed on my end.
