### ISSUE TITLE
failed to run on-target setarch x86_64 bash -x

### ISSUE THREAD

**Issue by wkibbler** [devrandom/gitian-builder#205]
i keep getting this error when trying to run the build script

Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:164:in `build_one_configuration'
        from ./bin/gbuild:309:in `block (2 levels) in <main>'
        from ./bin/gbuild:304:in `each'
        from ./bin/gbuild:304:in `block in <main>'
        from ./bin/gbuild:302:in `each'
        from ./bin/gbuild:302:in `<main>'

i think its an error with miniupnpc because the build.log contains this at the end
/home/ubuntu/build/raven/depends/work/download/miniupnpc-2.0.20170509/miniupnpc-2.0.20170509.tar.gz.temp: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Fetching miniupnpc-2.0.20170509.tar.gz from
curl: (3) <url> malformed
make: *** [/home/ubuntu/cache/common/download-stamps/.stamp_fetched-miniupnpc-miniupnpc-2.0.20170509.tar.gz.hash] Error 3

and ive tried downloading multiple versions of miniupnpc and checking them with their sha256sum hash and i get the same error every time

**Comment by rbuckhoy** [comment]
I get the same error with build.log output: 

+ mkdir -p /home/ubuntu/out/src
+ tar -x -C /home/ubuntu/out/src
+ git archive HEAD
+ cp /home/ubuntu/out/src/doc/README_windows.txt /home/ubuntu/out/readme.txt
cp: cannot stat `/home/ubuntu/out/src/doc/README_windows.txt': No such file or directory

**Comment by gwpreggae** [comment]
So there was no resolution to this? I'm getting "Failed to run on-target setarch" errors at building windows exec file from linux debian vm

**Comment by caesar-ski** [comment]
Did you figure this out? I am stuck here too.

**Comment by codenlighten** [comment]
Nope unfortunately not.

**Comment by devrandom** [comment]
This looks like an issue for the specific project using gitian, rather than gitian itself
