### ISSUE TITLE
failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)

### ISSUE THREAD

**Issue by cisociall** [devrandom/gitian-builder#207]
When i try to build with docker and bionic version ,at the last step, i lived this error.
What must i do. With trusty version i didn't live any problem but when bionic version this error appear.
Thanks!

Running build script (log in var/build.log)
Traceback (most recent call last):
	6: from bin/gbuild:302:in `<main>'
	5: from bin/gbuild:302:in `each'
	4: from bin/gbuild:304:in `block in <main>'
	3: from bin/gbuild:304:in `each'
	2: from bin/gbuild:309:in `block (2 levels) in <main>'
	1: from bin/gbuild:164:in `build_one_configuration'
bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)

This is my build.log
-------------------------------
+ set -e
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ umask 002
+ export OUTDIR=/home/ubuntu/out
+ OUTDIR=/home/ubuntu/out
+ GBUILD_BITS=64
+ GBUILD_CACHE_ENABLED=1
+ GBUILD_PACKAGE_CACHE=/home/ubuntu/cache/sudo-linux-0.13
+ GBUILD_COMMON_CACHE=/home/ubuntu/cache/common
+ MAKEOPTS=(-j2)
+ cd build/sudo
+ git reset -q --hard
+ git clean -q -f -d
+ REFERENCE_DATETIME='2019-02-03 14:10:55'
+ REFERENCE_DATE=2019-02-03
+ REFERENCE_TIME=14:10:55
+ cd build
+ WRAP_DIR=/home/ubuntu/wrapped
+ HOSTS='i686-pc-linux-gnu x86_64-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu'
+ CONFIGFLAGS='--enable-glibc-back-compat --enable-reduce-exports --disable-bench --disable-gui-tests'
+ FAKETIME_HOST_PROGS=
+ FAKETIME_PROGS='date ar ranlib nm'
+ HOST_CFLAGS='-O2 -g'
+ HOST_CXXFLAGS='-O2 -g'
+ HOST_LDFLAGS=-static-libstdc++
+ export QT_RCC_TEST=1
+ QT_RCC_TEST=1
+ export GZIP=-9n
+ GZIP=-9n
+ export 'TAR_OPTIONS=--mtime=2019-02-03\ 14:10:55'
+ TAR_OPTIONS='--mtime=2019-02-03\ 14:10:55'
+ export TZ=UTC
+ TZ=UTC
++ pwd
+ export BUILD_DIR=/home/ubuntu/build
+ BUILD_DIR=/home/ubuntu/build
+ mkdir -p /home/ubuntu/wrapped
+ test -n 1
+ export SOURCES_PATH=/home/ubuntu/cache/common
+ SOURCES_PATH=/home/ubuntu/cache/common
+ export BASE_CACHE=/home/ubuntu/cache/sudo-linux-0.13/depends
+ BASE_CACHE=/home/ubuntu/cache/sudo-linux-0.13/depends
+ mkdir -p /home/ubuntu/cache/sudo-linux-0.13/depends /home/ubuntu/cache/common
+ CONFIGFLAGS='--enable-glibc-back-compat --enable-reduce-exports --disable-bench --disable-gui-tests --enable-ccache'
+ export CCACHE_DIR=/home/ubuntu/cache/sudo-linux-0.13/ccache
+ CCACHE_DIR=/home/ubuntu/cache/sudo-linux-0.13/ccache
+ export CCACHE_COMPILERCHECK=content
+ CCACHE_COMPILERCHECK=content
+ '[' -f /home/ubuntu/cache/sudo-linux-0.13/ccache.tar ']'
+ export CCACHE_COMPRESS=1
+ CCACHE_COMPRESS=1
++ gcc --version
++ head -1
+ GCCVERSION='gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0'
+ export PATH_orig=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH_orig=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ create_global_faketime_wrappers '2000-01-01 12:00:00'
+ for prog in ${FAKETIME_PROGS}
+ echo '#!/bin/bash'
+ echo '# GCCVERSION=gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0'
+ echo 'REAL=`which -a date | grep -v /home/ubuntu/wrapped/date | head -1`'
+ echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1'
+ echo 'export FAKETIME="2000-01-01 12:00:00"'
+ echo '$REAL $@'
+ chmod +x /home/ubuntu/wrapped/date
+ touch -d '2019-02-03 14:10:55' /home/ubuntu/wrapped/date
+ for prog in ${FAKETIME_PROGS}
+ echo '#!/bin/bash'
+ echo '# GCCVERSION=gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0'
+ echo 'REAL=`which -a ar | grep -v /home/ubuntu/wrapped/ar | head -1`'
+ echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1'
+ echo 'export FAKETIME="2000-01-01 12:00:00"'
+ echo '$REAL $@'
+ chmod +x /home/ubuntu/wrapped/ar
+ touch -d '2019-02-03 14:10:55' /home/ubuntu/wrapped/ar
+ for prog in ${FAKETIME_PROGS}
+ echo '#!/bin/bash'
+ echo '# GCCVERSION=gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0'
+ echo 'REAL=`which -a ranlib | grep -v /home/ubuntu/wrapped/ranlib | head -1`'
+ echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1'
+ echo 'export FAKETIME="2000-01-01 12:00:00"'
+ echo '$REAL $@'
+ chmod +x /home/ubuntu/wrapped/ranlib
+ touch -d '2019-02-03 14:10:55' /home/ubuntu/wrapped/ranlib
+ for prog in ${FAKETIME_PROGS}
+ echo '#!/bin/bash'
+ echo '# GCCVERSION=gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0'
+ echo 'REAL=`which -a nm | grep -v /home/ubuntu/wrapped/nm | head -1`'
+ echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1'
+ echo 'export FAKETIME="2000-01-01 12:00:00"'
+ echo '$REAL $@'
+ chmod +x /home/ubuntu/wrapped/nm
+ touch -d '2019-02-03 14:10:55' /home/ubuntu/wrapped/nm
+ create_per-host_faketime_wrappers '2000-01-01 12:00:00'
+ for i in $HOSTS
+ for i in $HOSTS
+ for i in $HOSTS
+ for i in $HOSTS
+ export PATH=/home/ubuntu/wrapped:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/home/ubuntu/wrapped:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ EXTRA_INCLUDES_BASE=/home/ubuntu/wrapped/extra_includes
+ mkdir -p /home/ubuntu/wrapped/extra_includes
+ mkdir -p /home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu
+ rm -f /home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu/asm
+ ln -s /usr/include/x86_64-linux-gnu/asm /home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu/asm
+ for prog in gcc g++
+ rm -f /home/ubuntu/wrapped/gcc
+ cat
++ which -a gcc
++ grep -v /home/ubuntu/wrapped/gcc
++ head -1
+ chmod +x /home/ubuntu/wrapped/gcc
+ touch -d '2019-02-03 14:10:55' /home/ubuntu/wrapped/gcc
+ for prog in gcc g++
+ rm -f /home/ubuntu/wrapped/g++
+ cat
++ which -a g++
++ grep -v /home/ubuntu/wrapped/g++
++ head -1
+ chmod +x /home/ubuntu/wrapped/g++
+ touch -d '2019-02-03 14:10:55' /home/ubuntu/wrapped/g++
+ cd sudo
++ pwd
+ BASEPREFIX=/home/ubuntu/build/sudo/depends
+ for i in $HOSTS
+ EXTRA_INCLUDES=/home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu
+ '[' -d /home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu ']'
+ export HOST_ID_SALT=/home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu
+ HOST_ID_SALT=/home/ubuntu/wrapped/extra_includes/i686-pc-linux-gnu
+ make -j2 -C /home/ubuntu/build/sudo/depends HOST=i686-pc-linux-gnu
make: *** No targets specified and no makefile found.  Stop.
make: Entering directory '/home/ubuntu/build/sudo/depends'
make: Leaving directory '/home/ubuntu/build/sudo/depends'

**Comment by Ciip1996** [comment]
same issue

**Comment by devrandom** [comment]
This sounds like a question for the project that developed the descriptor / build script, and not for this project.

**Comment by Giszmo** [comment]
You might close the issue then? OP didn't reply in over a year ...

This is not the only issue that looks like it should be closed.
