### ISSUE TITLE
No longer fetching from remote

### ISSUE THREAD

**Issue by MitchellCash** [devrandom/gitian-builder#217]
In relation to #210, I notice it is no longer fetching from the remote as part of the build process

I tend to work on a branch and pass that branch name with a local repo to gitian to build. Without this feature I just finished a set of builds without realising it was building on an old commit from the branch.

Hoping there is a way to find some middle ground between @ultimaweapon's needs and still fetching a branch to get the latest HEAD of the branch without the manual interaction.

Is the best solution for now to manually fetch the latest source by:

```
cd inputs/<repo>
git fetch
```

and then run my build commands?

My usual build arguments are `--url` where I pass in a local repo (outside of the `inputs` folder) and the branch name to `--commit`.

**Comment by MitchellCash** [comment]
Or I could create a symbolic link from my working repo on the filesytem to the `inputs` dir?

**Comment by ultimaweapon** [comment]
Yes both should works. My idea is adding a new command line argument something like `--skip-update` to disable fetching from remote and revert the behavior back to the previous one.

**Comment by MitchellCash** [comment]
@ultimaweapon I think that sounds reasonable. Pull request opened for review.
