### ISSUE TITLE
Can't get gbuild to work on litecoin clone

### ISSUE THREAD

**Issue by gwpreggae** [devrandom/gitian-builder#225]
Thanks so much in advance. Any ideas? Im using debian vm
this is my repository..
https://github.com/Rascoin-Project/rascoin.git

 Here's my output:

debian@debian:~/gitian-builder$ ./bin/gbuild ../rascoin/contrib/gitian-descriptors/boost-win32.yml
sha256sum: boost_1_55_0.tar.bz2: No such file or directory
sha256sum: boost-mingw-gas-cross-compile-2013-03-03.patch: No such file or directory
--- Building for precise amd64 ---
Stopping target if it is up
Making a new image copy
lxc-execute: failed to open log file "/var/lib/lxc/gitian/gitian.log" : No such file or directory
sudo: unable to resolve host gitian
stdin: is not a tty
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog* ubuntu-minimal*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1289 kB disk space will be freed.
(Reading database ... 16075 files and directories currently installed.)
Removing ubuntu-minimal ...
Removing rsyslog ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Purging configuration files for rsyslog ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed.
Processing triggers for ureadahead ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
tar: boost_1_55_0.tar.bz2: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
tar: boost-mingw-gas-cross-compile-2013-03-03.patch: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
Upgrading system, may take a while (log in var/install.log)
Creating package manifest
stdin: is not a tty
Creating build script (var/build-script)
Running build script (log in var/build.log)
./bin/gbuild:23:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
 from ./bin/gbuild:169:in `build_one_configuration'
 from ./bin/gbuild:320:in `block (2 levels) in <main>'
 from ./bin/gbuild:315:in `each'
 from ./bin/gbuild:315:in `block in <main>'
 from ./bin/gbuild:313:in `each'
 from ./bin/gbuild:313:in `<main>'
debian@debian:~/gitian-builder$

**Comment by devrandom** [comment]
This looks like an issue for the specific project using gitian, rather than gitian itself
