### ISSUE TITLE
E: No such script: /usr/share/debootstrap/scripts/bionic

### ISSUE THREAD

**Issue by Giszmo** [devrandom/gitian-builder#233]
Trying to do a gitian build I followed the instructions [here](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md) to [create a virtualbox VM](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-create-vm-debian.md) and [setup gitian](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md) where I get to the part [Setting up the Gitian image](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-the-gitian-image) which fails with this error:

```
gitianuser@debian:~/gitian-builder$ bin/make-base-vm --lxc --arch amd64 --suite bionic
[sudo] password for gitianuser: 
E: No such script: /usr/share/debootstrap/scripts/bionic
```

I had originally filed [an issue in bitcoin-core/docs](https://github.com/bitcoin-core/docs/issues/62) but it appears to be a gitian-builder issue, right?

Following the [LXC instructions here](https://github.com/devrandom/gitian-builder#lxc) I get a slightly different error:

```
E: No such script: /usr/share/debootstrap/scripts/xenial
```

### Additional Debug Information

```
# history
    1  echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-start" > /etc/sudoers.d/gitian-lxc
    2  echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-execute" >> /etc/sudoers.d/gitian-lxc
    3  echo '#!/bin/sh -e' > /etc/rc.local
    4  echo 'brctl addbr br0' >> /etc/rc.local
    5  echo 'ip addr add 10.0.3.1/24 broadcast 10.0.3.255 dev br0' >> /etc/rc.local
    6  echo 'ip link set br0 up' >> /etc/rc.local
    7  echo 'firewall-cmd --zone=trusted --add-interface=br0' >> /etc/rc.local
    8  echo 'exit 0' >> /etc/rc.local
    9  chmod +x /etc/rc.local
   10  echo 'export USE_LXC=1' >> /home/gitianuser/.profile
   11  echo 'export GITIAN_HOST_IP=10.0.3.1' >> /home/gitianuser/.profile
   12  echo 'export LXC_GUEST_IP=10.0.3.5' >> /home/gitianuser/.profile
   13  reboot
$ history
    1  mkdir .ssh
    2  vi .ssh/authorized_keys
    3  sudo apt-get install git ruby apt-cacher-ng qemu-utils debootstrap lxc python-cheetah parted kpartx bridge-utils make ubuntu-archive-keyring curl firewalld
    4  sudo -s
    5  wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz
    6  echo "76cbf8c52c391160b2641e7120dbade5afded713afaa6032f733a261f13e6a8e  vm-builder_0.12.4+bzr494.orig.tar.gz" | sha256sum -c
    7  tar -zxvf vm-builder_0.12.4+bzr494.orig.tar.gz
    8  cd vm-builder-0.12.4+bzr494
    9  sudo python setup.py install
   10  cd ..
   11  git clone https://github.com/devrandom/gitian-builder.git
   12  git clone https://github.com/bitcoin/bitcoin
   13  git clone https://github.com/bitcoin-core/gitian.sigs.git
   14  git clone https://github.com/bitcoin-core/bitcoin-detached-sigs.git
   15  cd gitian-builder
   16  bin/make-base-vm --lxc --arch amd64 --suite bionic # For releases after and including 0.17.0
   17  bin/make-base-vm --lxc --arch amd64 --suite trusty # For releases before 0.17.0
$ ls /usr/share/debootstrap/scripts/{bionic,trusty}
ls: cannot access /usr/share/debootstrap/scripts/bionic: No such file or directory
/usr/share/debootstrap/scripts/trusty
```

**Comment by devrandom** [comment]
looks like it should be available on Debian buster - https://packages.debian.org/buster/all/debootstrap/filelist.

what version are you on?

**Comment by Giszmo** [comment]
I followed [those instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md?rgh-link-date=2020-08-29T22%3A55%3A18Z) which instructs to install Debian 8.10 (Jessie). Is that the issue?

**Comment by Giszmo** [comment]
So after commenting out $MIRROR in bin/make-base-vm and using `jessie` instead of `bionic` in above command, I run into a different error:

```
$ bin/make-base-vm --lxc --arch amd64 --suite jessie
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
I: Valid Release signature (key id 126C0D24BD8A2942CC7DF8AC7638D0442B90D010)
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: acl adduser dmsetup insserv libaudit1 libaudit-common libbz2-1.0 libcap2 libcap2-bin libcryptsetup4 libdb5.3 libdebconfclient0 libdevmapper1.02.1 libgcrypt20 libgpg-error0 libkmod2 libncursesw5 libprocps3 libsemanage1 libsemanage-common libslang2 libsystemd0 libudev1 libustr-1.0-1 procps systemd systemd-sysv udev 
I: Found additional base dependencies: binutils bzip2 cpp cpp-4.9 cron dh-python dpkg-dev g++ g++-4.9 gcc gcc-4.9 git-man libapparmor1 libapr1 libaprutil1 libasan1 libatomic1 libc6-dev libc-dev-bin libcilkrts5 libcloog-isl4 libcurl3-gnutls libdns-export100 libdpkg-perl liberror-perl libexpat1 libffi6 libgcc-4.9-dev libgmp10 libgnutls-deb0-28 libgnutls-openssl27 libgomp1 libgssapi-krb5-2 libhogweed2 libicu52 libidn11 libirs-export91 libisccfg-export90 libisc-export95 libisl10 libitm1 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 liblsan0 libmnl0 libmpc3 libmpdec2 libmpfr4 libnetfilter-acct1 libnettle4 libnfnetlink0 libp11-kit0 libpci3 libpsl0 libpython2.7-minimal libpython2.7-stdlib libpython3.4-minimal libpython3.4-stdlib libpython3-stdlib libpython-stdlib libquadmath0 librtmp1 libsasl2-2 libsasl2-modules-db libseccomp2 libserf-1-1 libsqlite3-0 libssh2-1 libstdc++-4.9-dev libsvn1 libtasn1-6 libtimedate-perl libtsan0 libubsan0 linux-libc-dev make mime-support patch perl perl-modules python python2.7 python2.7-minimal python3 python3.4 python3.4-minimal python3-minimal python-minimal xz-utils 
I: Checking component main on http://ftp.us.debian.org/debian...
E: Couldn't find these debs: language-pack-en
```

**Comment by Giszmo** [comment]
I just want to verify bitcoin-core and I'm a bit confused about what I'm doing. So I created a debian VM to run a script to create an Ubuntu VM for the builds?

**Comment by devrandom** [comment]
OK, I haven't actually seen the most recent Bitcoin Core instructions.

So for Gitian building, you have a host OS, which is either Debian or Ubuntu, and then the Gitian process itself creates a guest VM.  For Bitcoin Core, the guest VM always uses the Ubuntu Bionic OS - see https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-descriptors/gitian-linux.yml#L6 .

The instructions you linked above further have you create a VM to contain the host OS.  The only reason to do so is if you are running an OS on your machine that is not suitable - e.g. if it's MacOS or not the right version of Debian or Ubuntu.

If the Bitcoin Core instructions say to install Jessie on the host VM, and Jessie is missing the Bionic deboostrap config, then this is likely a bug in the instructions.  I would try with a more recent version of Debian, or perhaps with Ubuntu Bionic (which obviously would have the right deboostrap config).

Sorry, this is somewhat confusing given the multiple VM layers.

**Comment by MarcoFalke** [comment]
Yeah, our docs might need to be bumped for a more recent version of debian

**Comment by Giszmo** [comment]
I would close this issue for now then, especially as @MarcoFalke should be aware of it and might fix it on the bitcoincore documentation side for the next guy.

> The instructions you linked above further have you create a VM to contain the host OS. The only reason to do so is if you are running an OS on your machine that is not suitable

I re-build dozens of apps, all with their own build instructions and I like to install as little as possible on my host system, so I jumped for the VM approach although my host is Ubuntu 20.4.
