### ISSUE TITLE
Ubuntu 20.04 weirdness and errors with lxc

### ISSUE THREAD

**Issue by miketwenty1** [devrandom/gitian-builder#235]
Looking at docs from here and https://github.com/bitcoin-core/docs/tree/master/gitian-building
Using the Debian guides seems to result ultimately in some errors for lxc.

Tried the more manual approach and the automated [python script](https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-build.py) Both seem to result in the same errors to the terminal output.

This currently produced with the python script from bitcoin core. specifying 0.20.1
```
(Reading database ... 18525 files and directories currently installed.)
Purging configuration files for rsyslog (8.32.0-1ubuntu4) ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed
Processing triggers for systemd (237-3ubuntu10) ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
Preparing build environment
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
Upgrading system, may take a while (log in var/install.log)
Creating package manifest
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
Creating build script (var/build-script)
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.gitian"
lxc-execute: gitian: cgroups/cgfsng.c: mkdir_eexist_on_last: 1143 File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.gitian"
Running build script (log in var/build.log)
```

When I check `./bitcoin/gitian-builder/var/build.log`
I see it compiling a bunch of stuff.. however I expected this to run in a lxc container.. 
When I run `lxc list` I don't see the container running. 

I'm able to run test containers with lxc, so not sure what the issue is here. Tried modifying the /etc/subuid and /etc/subgid to no avail.

Is anyone running this on lxc/gitian ubuntu recently? If not is there a preferred OS/method of doing this?

**Comment by miketwenty1** [comment]
I would like to add some information:

even with the errors I was able to produce this assert which was plopped into `bitcoin/gitian.sigs/0.20.1-linux/tidwell/`
https://github.com/miketwenty1/images/blob/master/bitcoin-core-linux-0.20-build.assert

I see many of the gitian verifiers run on machines with different packages and what not, but produce the same tarballs.
I was able to produce most of the same tarballs. except the important ones I cared about.
I also did an analysis on the extracted binaries to see how much of a different there was. 

the files were the same exact size but 24 bytes were different.
```
cmp -l <bitcoind From Bitcoincore.org> <bitcoind I Created> | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
000002BD 3A 6B
000002BE 43 46
000002BF 9A 46
000002C0 31 17
000002C1 A5 F7
000002C2 15 F9
000002C3 7F 1F
000002C4 F7 D2
000002C5 05 70
000002C6 2E AC
000002C7 D3 86
000002C8 10 F4
000002C9 05 3E
000002CA 0D F4
000002CB F5 A5
000002CC 64 8E
000002CD 3A EE
000002CE 02 ED
000002CF EA FF
000002D0 3F 19
009D5115 11 B2
009D5116 4D 5C
009D5117 51 EE
009D5118 9D BB
```

I see lxc / docker / kvm / virtualbox all being said to be good methods. 
I see Ubuntu, Debian said to work (no version specified) with the automated python script. Fedora also said to be a usable OS. 

4 questions:
- Are the errors I received with lxc expected?
- Was this actually supposed to run in a lxc container, but failed so it ran on the bare metal?
- Is Lxc a reliable method?
- If not sure if there's a defacto reliable way of doing this?

**Comment by luke-jr** [comment]
Note your offsets are off by one.

The first range is `.note.gnu.build-in`, and the second is in `.gnu_debuglink`

**Comment by miketwenty1** [comment]
@luke-jr is this a side note in reference to the output? (i.e. wouldn't fix the problem right)?

**Comment by miketwenty1** [comment]
https://bitcoin.stackexchange.com/questions/99967/reproducible-gitian-builds-but-not-the-same-hash-as-bitcoincore-org?noredirect=1#comment113370_99967
