### ISSUE TITLE
Checking out source as `tobuild` is not ideal

### ISSUE THREAD

**Issue by abitmore** [devrandom/gitian-builder#243]
Since #239, gitian builder checks out the target tag, branch or commit as a new `tobuild` tag for building, which is not ideal, because it modifies data in the local git repository. Specifically, by doing so, the `git describe --tags` command (probably used in source code or build wrapper scripts) may return `tobuild` unexpectedly (E.G. [this code](https://github.com/bitshares/bitshares-gitian/blob/7a2ce27ca7e4eed2f261138efa3cf83516ff2e70/descriptors/bitshares-core-linux.yml#L106) (it would be patched later to remove the new tag before building)).

**Comment by devrandom** [comment]
See proposed fix linked above.
