### ISSUE TITLE
Problems compiling a crypto.

### ISSUE THREAD

**Issue by IdotMaster1** [devrandom/gitian-builder#246]
Hello! I am trying to build a cryptocurrency with gitian but i am having some issues.
This is the "log"

sha256sum: qt-win32-4.8.5-gitian-r8.zip: No such file or directory
--- Building for precise amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian
stdin: is not a tty
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog* ubuntu-minimal*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1289 kB disk space will be freed.
(Reading database ... 16075 files and directories currently installed.)
Removing ubuntu-minimal ...
Removing rsyslog ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Purging configuration files for rsyslog ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed.
Processing triggers for ureadahead ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
tar: qt-win32-4.8.5-gitian-r8.zip: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
Upgrading system, may take a while (log in var/install.log)
Creating package manifest
stdin: is not a tty
Creating build script (var/build-script)
Running build script (log in var/build.log)
./bin/gbuild:23:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:185:in `build_one_configuration'
        from ./bin/gbuild:339:in `block (2 levels) in <main>'
        from ./bin/gbuild:334:in `each'
        from ./bin/gbuild:334:in `block in <main>'
        from ./bin/gbuild:332:in `each'
        from ./bin/gbuild:332:in `<main>'

**Comment by jxmiecole** [comment]
This doesnt show the error. The error is accessed in gitian-builder/var/build.log
