### ISSUE TITLE
must specify a commit for directory

### ISSUE THREAD

**Issue by TabbsCommunity** [devrandom/gitian-builder#247]
Hey people I created my own cryptocurrency and I want to compile it for windows I did all steps but at the last step it fails I run
./bin/gbuild --commit Bandex=v1.0 ../Bandex/contrib/gitian-descriptors/gitian-win32.yml
and the output I get is
rib/gitian-descriptors/gitian-win32.yml
./bin/gbuild:310:in `block in <main>': must specify a commit for directory bandex (RuntimeError)
        from ./bin/gbuild:307:in `each'
        from ./bin/gbuild:307:in `<main>'
Thx for helping :)

**Comment by BaconSansGluten** [comment]
same pronlem here

**Comment by devrandom** [comment]
did you try lower case `bandex` on the command line?

**Comment by TabbsCommunity** [comment]
I found the problem guys, sometimes the makefile in depends disappears without reason so now it's working.

**Comment by devrandom** [comment]
doesn't seem like it's a problem in gitian itself, so closing for now
