### ISSUE TITLE
`system!': failed to run on-target -u root apt-get update Error

### ISSUE THREAD

**Issue by Vitalik-Hakim** [devrandom/gitian-builder#272]
I am trying to fix this error. and I don't know-how.
the install log says some "get" files are missing but I don't know whether it is the problem.
Please below is the error.
Please help😣 . I need for my personal project. Thanks in Advance

Starting target
Checking if target is up
Preparing build environment
Updating apt-get repository (log in var/install.log)
./bin/gbuild:23:in `system!': failed to run on-target -u root apt-get update >> var/install.log 2>&1 (RuntimeError)
        from ./bin/gbuild:117:in `build_one_configuration'
        from ./bin/gbuild:341:in `block (2 levels) in <main>'
        from ./bin/gbuild:336:in `each'
        from ./bin/gbuild:336:in `block in <main>'
        from ./bin/gbuild:334:in `each'
        from ./bin/gbuild:334:in `<main>'

**Comment by Vitalik-Hakim** [comment]
Its okay. I fixed it.

**Comment by Kailkox** [comment]
Its working? Had you problems with mine error?

**Comment by dotada** [comment]
> Delete the initial gitian-builder github clone and clone it again. It has been fixed

I tried that but it still wouldn't work. Any ideas?
