### ISSUE TITLE
cannot set terminal process group (-1): Inappropriate ioctl for device

### ISSUE THREAD

**Issue by stapler117** [devrandom/gitian-builder#63]
I've successfully completed a couple of gitian builds for Dogecoin, but as of recently, I've been getting an error that Google shows affected the su command in a particular version of Debian. This occurred after I pulled a more recent version of gitian-builder, but the issue still persists after checking out older commits.  I am running ubuntu server 14.04 on a fresh VM. Creating the base VM's for gitian appears to work fine. I'm using LXC and here is the output.

user@gitian:~/gitian-builder$ ./bin/gbuild ../dogecoin/contrib/gitian-descriptors/deps-linux.yml
--- Building for precise i386 ---
Stopping target if it is up
Making a new image copy
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
root@gitian:~# exit
Starting target
Checking if target is up
Preparing build environment
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@gitian:~$ exit
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --log-priority options.
./bin/gbuild:21:in `system!': failed to run copy-to-target  inputs/openssl-1.0.1h.tar.gz build/ (RuntimeError)
        from ./bin/gbuild:80:in `block in build_one_configuration'
        from ./bin/gbuild:78:in `each'
        from ./bin/gbuild:78:in `build_one_configuration'
        from ./bin/gbuild:235:in `block (2 levels) in <main>'
        from ./bin/gbuild:230:in `each'
        from ./bin/gbuild:230:in `block in <main>'
        from ./bin/gbuild:228:in `each'
        from ./bin/gbuild:228:in `<main>'

**Comment by devrandom** [comment]
Assuming this is fixed, please reopen if not.
