### ISSUE TITLE
make-base-vm should use losetup -d instead of kpartx -d to remove loop

### ISSUE THREAD

**Issue by midnightmagic** [devrandom/gitian-builder#75]
found a bug in the gitian builder that's been haunting me for maybe a week. in gitian-builder/bin/make-base-vm kpartx is used to configure a loopback device which allows us to copy a single raw partition into a build image for use with LXC. During cleanup, kpartx -d /dev/loop${loop} is used, but in multipath-tools 0.4.9 (which is on ubuntu 12.04.x) kpartx fails when using the /dev/loop${loop} syntax, it has to be given the file-side mapping. losetup -d /dev/loop${loop} will work, as will kpartx -d /path/to/image.raw. test results:

```
masheen 00:21:44 /v/soft/tbb/gitian-builder# kpartx -av $OUT.raw|sed -n '/loop.p1/{s/.*loop\(.\)p1.*/\1/;p}'
0
masheen 00:23:11 /v/soft/tbb/gitian-builder# losetup -a
/dev/loop0: [0811]:1667076 (base-precise-amd64.raw)
masheen 00:23:15 /v/soft/tbb/gitian-builder# kpartx -d /dev/loop0
masheen 00:23:27 /v/soft/tbb/gitian-builder# losetup -a
/dev/loop0: [0811]:1667076 (base-precise-amd64.raw)
masheen 00:23:34 /v/soft/tbb/gitian-builder# kpartx -d base-precise-amd64.raw 
loop deleted : /dev/loop0
masheen 00:23:42 /v/soft/tbb/gitian-builder# losetup -a
masheen 00:23:44 /v/soft/tbb/gitian-builder#
```

This means that multiple build runs will eventually fill loop devices, holding open old images (and thus eating disk space) and in particular ***old builds will still hang around and potentially interfere with future builds because it's possible for on-target to execute against the old, failed-to-delete mapping***

**Comment by devrandom** [comment]
sorry, I overlooked this.  is there a patch / pull request available?

**Comment by devrandom** [comment]
I'm not seeing the issue you reported on Ubuntu 14.10.  I just ran a make-base-vm and `losetup -a` is clean after.

**Comment by midnightmagic** [comment]
The issue is twofold;

1) The system can get into a state where kpartx does not cleanly unmount a loop device.
2) If the loopback table is full, it will continue anyway and use someone else's loop device. (Or so it seems.)

**Comment by midnightmagic** [comment]
af56f89a6acffd363c845a489ec163f0d85d30be may correct this issue as well.

**Comment by devrandom** [comment]
Please reopen if still relevant.
