### ISSUE TITLE
`tar`'s `-k` option behavior changed in version 1.27, breaking `copy-from-host` when destination files already exist.

### ISSUE THREAD

**Issue by Michagogo** [devrandom/gitian-builder#80]
When gbuilding, when trying to `copy-from-host` any files that already exist, the error mentioned above causes the build to fail (on Ubuntu 14.04 with LXC). This happened both with the source tarball on the second (amd64) build of [Bitcoin Core v0.9.4](https://github.com/bitcoin/bitcoin/blob/v0.9.4/contrib/gitian-descriptors/gitian-linux.yml) and with what looks like all of the cache when using the cache. It looks like the problem is that the `-k` option is used with `tar` in `copy-from-host`. What I can't figure out, though, is why this issue hasn't come up earlier.

**Comment by Michagogo** [comment]
Aha. Found it! http://git.savannah.gnu.org/cgit/tar.git/plain/NEWS?id=release_1_27

>* The --keep-old-files and --skip-old-files options.
>
>This release restores the traditional functionality of the
>--keep-old-files.  This option causes tar to avoid replacing
>existing files while extracting and to treat such files as errors.
>Tar will emit a prominent error message upon encountering such files
>and will exit with code 2 when finished extracting the archive.
>
>A new option --skip-old-files is introduced, which acts exactly as
>--keep-old-files, except that it does not treat existing files as
>errors.  Instead it just silently skips them.  An additional level of
>verbosity can be obtained by using the option --warning=existing-file
>together with this option.

Precise has tar 1.26-4ubuntu1. Trusty has 1.27.1-1.

**Comment by Michagogo** [comment]
So it looks to me like the necessary change is to replace `-k` with `--skip-old-files`, if I'm not mistaken. The question, then, is this: how can we detect whether we're using tar 1.26 and should use -k, or using 1.27 and should use --skip-old-files?

**Comment by Michagogo** [comment]
Confirmed that replacing `-xkf` with `--skip-old-files -xf` seems to work. The problem, then, is figuring out which version to use...

**Comment by devrandom** [comment]
Should we perhaps overwrite old files instead?

**Comment by Michagogo** [comment]
Not sure. Also, @theuni brought up a good point in IRC: why are we using
tar anyway? Are there other, better options?

**Comment by devrandom** [comment]
`rsync` or `rsync --delete` might be of interest here.  Is this for the cache read-out?

**Comment by Michagogo** [comment]
It's for copy-from-target, wherever that's used. I noticed it first in
extracting the cache at the end of a build, but I also noticed it when
building 0.9.4 for linux, which uses 2 VMs, building for 32- and 64-bit
each in their own VM, and each build yields a source tarball, which caused
the conflict when it tried to pull out the second one.

**Comment by devrandom** [comment]
Hm.... I think maybe for that usecase overwriting is good enough.  So `--overwrite` for a simple fix?

**Comment by Michagogo** [comment]
Isn't overwriting the default, in tar? I assumed that if there was a flag
there, it had been inserted for a reason. I think we need to figure out if
there's anything that we might copy from the target that we wouldn't want
to overwrite... And if we change behavior, probably should also change the
non-LXC version to match.

**Comment by Michagogo** [comment]
Also, just noticed in the original issue I said copy-from-host when I meant copy-from-target. Will fix tomorrow.

**Comment by devrandom** [comment]
Yes, actually I think it is the default, although I don't see it mentioned in the tar docs.

**Comment by devrandom** [comment]
Also, I see/remember that the KVM version uses scp, which overwrites.  So I'm strongly leaning towards changing the LXC one to match.  Anybody see an issue with that?  @theuni ?

**Comment by devrandom** [comment]
OK, went ahead and removed the -k
