### ISSUE TITLE
E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by josephbisch** [devrandom/gitian-builder#84]
There is an issue that appears to have been incorrectly reported as an issue with Bitcoin Core: bitcoin/bitcoin#5930. It really seems to be an issue with gitian-builder. As the linked issue states, someone is having an issue with LXC and precise. I am having the same issue with LXC and trusty. The error message is:

`E: Unable to correct problems, you have held broken packages.`

I am trying to build different software (Armory) and that is why I don't think this is a Bitcoin Core specific issue.

There is no indication that anything is wrong from the logs. Just this error message to the host's console.

I don't have this issue with KVM. I'm not sure about the person that originally reported the issue under the Bitcoin Core repo.

**Comment by nullpt** [comment]
The error is the same both for KVM and LXC using on my Ubuntu 14.04 (trusty) host.

There is a  workaround - to disable package re-installing on a target VM. I just commented out a command `dpkg-query...` in the [`target-bin/grab-packages.sh`](https://github.com/devrandom/gitian-builder/blob/master/target-bin/grab-packages.sh#L11) script.

Actually I don't understand a purpose for this command, because a new VM is being created on each build. But I found another reference to grab-packages.sh in an issue #45

**Comment by josephbisch** [comment]
Hm, I am experiencing this issue with KVM now, so I'm not sure why I wasn't before.

See [this assert file](https://github.com/bitcoin/gitian.sigs/blob/master/0.10.0-linux/aschildbach/bitcoin-linux-0.10-build.assert) as an example of an assert file. It shows the hashes of all the packages that are installed in the VM. It makes sense to include the hash of output files, but I'm not certain why the hashes of all the installed packages are included. Probably for analyzation purposes in the event that someone gets a different hash for the output file than the hash that everyone else gets.

I'm guessing that the packages are being redownloaded because maybe Ubuntu doesn't include preinstalled packages in the cache? So they have to be redownloaded so the hash can be calculated for all the packages (the line after the one you commented out). That's all a guess, but it's the only thing that seems to make sense to me.

I'm curious if the resulting assert file still has the hashes of all the packages? Maybe I'll see if I get a chance.

**Comment by josephbisch** [comment]
The particular Gitian descriptor I'm using isn't in a working state, so I couldn't get all the way through the build to generate an assert file, but var/base-trusty-amd64.manifest only has a few packages now (mostly the ones installed by the descriptor), so commenting out that line definitely affects the calculating of the hashes.

**Comment by nullpt** [comment]
As I understand, the error is caused by name conflicts for multi-arch packages. According to [dpkg-query (1)](http://manpages.debian.org/cgi-bin/man.cgi?sektion=1&query=dpkg-query&apropos=0&manpath=sid&locale=en) there should be `${binary:Package}` format specifier.

I works on my trusty host (see nullpt/gitian-builder@a2c56b8f2773b540c72a55fc7c30800a51ce8cc8), But the list of installed packages in `var/base-precise-amd64.manifest` is still short:

```
acd5652a728dd6d873fa5b3ba77dbc240b8386d47860489620726c2b6493e231  autoconf2.13_2.13-61_all.deb
7d1a4b47ed622f8f788e3cb9a399be50d571ab00ec434c929d623b73b44083db  autoconf_2.68-1ubuntu2_all.deb
c4a16cbd500f281547fed560e4dea441d7c2230407a414f3845bbf1fe2638eb9  automake_1%3a1.11.3-1ubuntu2_all.deb
489e3cd9f9f6d76b9aa52ec342b4d63f92fad4845c9b07a0ebc0e3bdfeb34e91  autotools-dev_20120210.1ubuntu1_all.deb
1c43be4685cf2814bfc29d1f3226d421ddd3a1fbedb00b572f2a730758b0d759  binutils-gold_2.22-6ubuntu1.2_amd64.deb
0bfc324ddf8a89f056f3e6d52749cd045e262b49e95819070f9132dfae04693e  bsdmainutils_8.2.3ubuntu1_amd64.deb
388149060bb0fc67bf49f7e17cec1319c8fa1faf7dc850ca678b10b27b67cdb0  faketime_0.8-1_amd64.deb
012e5788b8304314040988cf93040e9b00ae78def59b75a9bdaf37b283a5c2bb  g++-4.6-multilib_4.6.3-1ubuntu5_amd64.deb
aeb107425de0d935a547c6a93259b6ab6c863963e3e14d10346a6257b80d362a  gcc-4.6-multilib_4.6.3-1ubuntu5_amd64.deb
d150ffab7753c70db1636fd9584857ed1101d964b9040a59c4e2f630383ee74c  gcc-multilib_4%3a4.6.3-1ubuntu5_amd64.deb
8e502c8cbeb332079eb0d1b356e6211ac2e8f2bcd04593083451df1ff04a5a79  g++-multilib_4%3a4.6.3-1ubuntu5_amd64.deb
61f71d3422160c2a1f8914d32eee929398a31f3a62c377d256572476c9a03b2b  grub_0.97-29ubuntu66_amd64.deb
422a4f6a559a31011c520fe4f2f6f892dfb9c6c48c803f35cd887592d047b9e8  lib32gcc1_1%3a4.6.3-1ubuntu5_amd64.deb
8d94b3c501cf1ce730d830fa6a8f76c2d3ca3731eb6dfa21271a0c2a5be809e3  lib32gomp1_4.6.3-1ubuntu5_amd64.deb
aba08f3482c0388fed63ec64e6005baacc559e57d65a656e5b0fdb46d27f0792  lib32quadmath0_4.6.3-1ubuntu5_amd64.deb
1069f6231fe4c83f24b31cf60541680858b6c0658fe93f8db19464f5ab7fed81  lib32stdc++6_4.6.3-1ubuntu5_amd64.deb
bebc3783d16d62fa412f96f86f2c6cf01e9484cbc7f01add2934bd3d220ef026  libc6-dev-i386_2.15-0ubuntu10.11_amd64.deb
3bc7f8f025c2a2698f7f6de42faba0d0fbbac5cd1f3c356233ea2ad773313ea2  libc6-i386_2.15-0ubuntu10.11_amd64.deb
f76c467edd67fab02b2c03c74d281782af84f5a094cee824f510e9fb820de741  libtool_2.4.2-1ubuntu1_amd64.deb
e70c7fd9ae032c2d836351bf7b271e10828725bf7dd7a19e46b8b629ea0a7ad7  linux-image-3.2.0-77-virtual_3.2.0-77.114_amd64.deb
85185c86856a33fe7fdbb525ce6bd6b41e84be3b6681b6d6f232eb0c1c7ba933  linux-image-virtual_3.2.0.77.91_amd64.deb
93dbcb14256be5a950924e908b39cb39124ce17716bd9abb38b61de504d0e8f9  m4_1.4.16-2ubuntu1_amd64.deb
479ffffa689c6a2917c44b804e633a336f1d4b670042465d9b62501363d95003  pkg-config_0.26-1ubuntu1_amd64.deb
```

**Comment by josephbisch** [comment]
Hm, using `${binary:Package}` doesn't seem to be a good fix, because it seems like the manifest file just lists the packages specified in the gitian descriptor plus their dependencies (plus a few other packages like grub and the linux-image packages). So like you said, the list of installed packages is still short.

Maybe @devrandom has some insight into this.

**Comment by devrandom** [comment]
The purpose of grabbing the packages / hashing is to create an audit trail in case of a discrepancy or in case one of the signers is compromised.  I can see the current method in grab-packages.sh is heavy and error prone.  Perhaps it can use the --download-only flag - could you try that?

**Comment by devrandom** [comment]
grub was the issue.  Please try again.

I'm seeing now that the manifest has incorrect package versions, but that won't stop you from building.  Opened https://github.com/devrandom/gitian-builder/issues/85

**Comment by josephbisch** [comment]
The fix seems to work. I am now able to get to the point where the build script runs without having to comment out anything. I'm using a 64-bit trusty VM.

**Comment by nullpt** [comment]
Thanks! It works after base VM re-creating.

**Comment by devrandom** [comment]
hmm... it should have worked without re-creating.

**Comment by josephbisch** [comment]
It worked for me without recreating.

**Comment by devrandom** [comment]
Great.
