### ISSUE TITLE
Failure having to do with grub and upgrading

### ISSUE THREAD

**Issue by Michagogo** [devrandom/gitian-builder#86]
Some recent changes have to do with grub and/or upgrading the guest system before `gbuild`ing. Not sure what's going on exactly, but I'm having a problem where the `Upgrading system, may take a while` section took a while, and then failed with this message: `./bin/gbuild:21:in 'system!': failed to run on-target -u root bash < target-bin/upgrade-system.sh > var/install.log 2>&1 (RuntimeError)`.

Editing `upgrade-system.sh` to remove the redirections to files and `/dev/null` reveals that the `purge` of `grub` works, and the `dist-upgrade` seems to proceed normally, until this happens: https://www.irccloud.com/pastebin/xLjCr9YR

The weird thing is that I used `gbuild` last night and it worked without a problem, so I don't know what changed between last night and now.

Right now I've removed the base container and am rerunning `make-base-vm`, hoping that then there won't be anything to upgrade and I'll skip over this issue, but that shouldn't be necessary. Also, I noticed that there was some stuff that looked weird in `upgrade-system.sh` -- there seems to be two different redirects, both to `/dev/null` and to a log file. What's up with that?

**Comment by Michagogo** [comment]
Update: Rerunning make-base-vm worked, and I was able to build without that problem, and as of right now I was again able to build, still without this problem.

**Comment by devrandom** [comment]
This seems to be related to https://github.com/devrandom/gitian-builder/commit/7d1e7c5419121ed4e703902cce2c522fcc7097d3 .  Before this commit, the grub package was being picked up, which was causing issues with Ubuntu trusty.   However, it looks like the package change is not backwards compatible with existing VM images.  I don't have the bandwidth to look into the root cause right now.  The workaround is to recreate the base VM image.

**Comment by Michagogo** [comment]
Oh, I see. That's good to know... I was worried that I'd have to redo that every time package x got updated or something.

**Comment by Michagogo** [comment]
Wait, I thought grub is removed before the upgrade?

**Comment by devrandom** [comment]
Yes, `grub` is removed, but look like the replacement, `grub-pc` fails to install properly.

**Comment by Michagogo** [comment]
@devrandom Looks like it's not just a matter of backwards compatibility. It's happening again. Looking at the list of packages:
```
The following NEW packages will be installed:
  grub-gfxpayload-lists grub-pc grub2-common linux-image-3.2.0-83-generic
  linux-image-3.2.0-83-virtual
The following packages will be upgraded:
  apt apt-utils debootstrap dnsmasq-base dpkg dpkg-dev libapt-inst1.4
  libapt-pkg4.12 libcurl3-gnutls libdpkg-perl libssl1.0.0 libtasn1-3 libx11-6
  libx11-data libxext6 linux-image-generic linux-image-virtual linux-libc-dev
  ntpdate openssl tzdata
21 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
```

I'm trying to think what might be pulling it in, and I suspect it may have something to do with upgrading Linux...

**Comment by devrandom** [comment]
Please let me know here if this happens again.

**Comment by devrandom** [comment]
It seems like the root issue is that we don't need a kernel and grub on LXC, but vmbuilder doesn't know that.

Perhaps it's time to move to a different bootstrapping method, at least for LXC.

**Comment by Michagogo** [comment]
There's `lxc-create`, though when I tried figuring out how it works I ended
up confusing myself. There's a whole set of tools for LXC creation, use,
and management, a little more sophisticated than converting from a KVM
image and using `cp` to reset... If someone who actually knew how all that
worked were to take a look at gitian's LXC support, I suspect it would be
possible to make it work really well, as opposed to having a bunch of hacks
layered on top of each other.

**Comment by gurnec** [comment]
FWIW, I think I see what's going on here, at least in my case (an Ubuntu 12.04 container).

The `dist-upgrade` in `upgrade-system.sh` pulls in a new kernel image, and the kernel [has a dependency for a bootloader](http://packages.ubuntu.com/precise/linux-image-3.2.0-82-generic). Since a `purge grub` is done right before the `dist-upgrade` (and grub is one alternative for a bootloader), the preferred bootloader is brought in instead (grub-pc, another bootloader alternative).

**Comment by Michagogo** [comment]
Wait, but in that case, shouldn't it refuse to remove grub? Or rather,
automatically remove the kernel? I thought that if you remove a package it
also removes packages that depend on it (for an example, try telling
apt-get to remove something like Python or libc).

**Comment by gurnec** [comment]
@Michagogo That's the last time I'll try to analyze something on a Saturday night ;-)

You're right *again*, I just checked the link above, and it's not a *dependency*, just a *recommendation*. I don't have time to test this at the moment, but I suspect a much better idea would be to revert my entire commit, and then just add `--no-install-recommends` to the `apt-get dist-upgrade`. That would be much simpler and cleaner, if it works.

**Comment by devrandom** [comment]
I have a revamped support for LXC in the new `lxc` branch of this repo.  Please try it out, I think it might solve all our LXC issues.  It eliminates grub, the linux kernel and holds several packages that can cause issues on upgrade.

**Comment by gurnec** [comment]
@devrandom This looks great, thanks!

I tried building Bitcoin 0.10.1 (12.04 container on a 14.04 host), and ran into one blocking issue and two minor annoyances. I added comments to the commit with proposed small updates to fix what I ran into.

Although I only built the Windows binaries, I can confirm that they match the official release.

**Comment by devrandom** [comment]
I made some updates to the `lxc` branch...

**Comment by Michagogo** [comment]
Does debootstrap pull  from -updates and -security? I suspect not, since on first use of a freshly created container it needs to upgrade 122 packages and install 9 new ones.

**Comment by devrandom** [comment]
@Michagogo that's correct, it unfortunately does not.  Is that a concern?  You can use `gbuild -i` to reuse the updated container during development.

**Comment by Michagogo** [comment]
Well, it's just really annoying that it takes several times longer now to
gbuild Bitcoin Core releases, which is 3 different builds for each of the 3
OSes. And there's also the issue of it just failing, which I should be able
to tell you more about as soon as it happens again (assuming that happens).
It's running right now with a /dev/null redirect removed...

**Comment by devrandom** [comment]
Will look into improving this.
