### ISSUE TITLE
cp: cannot stat `base-lucid-amd64': No such file or directory

### ISSUE THREAD

**Issue by vertoe** [devrandom/gitian-builder#88]
I created base-vms for lucid and precice for both i386 and amd64 architectures.
But I can't use them:
```
vertoe@debian:~/gitian-builder$ make-clean-vm 
cp: cannot stat `base-lucid-amd64': No such file or directory
vertoe@debian:~/gitian-builder$ make-clean-vm --arch i386
cp: cannot stat `base-lucid-i386': No such file or directory
vertoe@debian:~/gitian-builder$ make-clean-vm --arch i386 --suite precise
cp: cannot stat `base-precise-i386': No such file or directory
vertoe@debian:~/gitian-builder$ make-clean-vm --arch amd64 --suite precise
cp: cannot stat `base-precise-amd64': No such file or directory
vertoe@debian:~/gitian-builder$ ls -lsha
total 2.9G
4.0K drwxr-xr-x 14 vertoe vertoe 4.0K May  6 13:26 .
4.0K drwxr-xr-x  7 vertoe vertoe 4.0K May  6 10:42 ..
649M -rw-r--r--  1 root   root   649M May  6 13:14 base-lucid-amd64.qcow2
589M -rw-r--r--  1 root   root   589M May  6 13:10 base-lucid-i386.qcow2
928M -rw-r--r--  1 root   root   928M May  6 13:26 base-precise-amd64.qcow2
783M -rw-r--r--  1 root   root   783M May  6 13:21 base-precise-i386.qcow2
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 09:36 bin
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 13:01 build
4.0K drwxr-xr-x  4 vertoe vertoe 4.0K May  6 11:06 cache
 36K -rw-r--r--  1 vertoe vertoe  35K May  6 09:36 COPYING
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 09:36 doc
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 09:36 etc
4.0K drwxr-xr-x  8 vertoe vertoe 4.0K May  6 13:01 .git
4.0K -rw-r--r--  1 vertoe vertoe  102 May  6 09:36 .gitignore
4.0K drwxr-xr-x  3 vertoe vertoe 4.0K May  6 11:29 inputs
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 09:36 libexec
4.0K -rw-r--r--  1 vertoe vertoe  932 May  6 09:36 LICENSE
8.0K -rw-r--r--  1 vertoe vertoe 5.7K May  6 09:36 README.md
4.0K -rw-r--r--  1 vertoe vertoe  881 May  6 09:36 RELEASE_NOTES
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 11:06 result
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 09:36 share
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 09:38 target-bin
4.0K -rw-r--r--  1 vertoe vertoe 1.3K May  6 09:36 Vagrantfile
4.0K drwxr-xr-x  2 vertoe vertoe 4.0K May  6 11:49 var
vertoe@debian:~/gitian-builder$ start-target 32 lucid-i386
vertoe@debian:~/gitian-builder$ on-target ls -lsha
lxc-start: No such file or directory - failed to get real path for '/home/vertoe/gitian-builder/target--'
lxc-start: failed to mount rootfs
lxc-start: failed to setup rootfs for 'gitian'
lxc-start: failed to setup the container
lxc-start: invalid sequence number 1. expected 2
lxc-start: failed to spawn 'gitian'
lxc-start: Device or resource busy - failed to remove cgroup '/sys/fs/cgroup//lxc/gitian'
```

I created them using the following commands:
https://gist.github.com/vertoe/2121b0a9b15e06c0c49e

Any idea what I'm doing wrong?

**Comment by vertoe** [comment]
Host is a debian 7.8 wheezy, running latest gitian from github master.

**Comment by vertoe** [comment]
Here is a stack while trying to gbuild bitcoin:

```
vertoe@debian:~/gitian-builder$     ./bin/gbuild --commit bitcoin=HEAD ../bitcoin/contrib/gitian-descriptors/gitian.yml
Initialized empty Git repository in /home/vertoe/gitian-builder/inputs/bitcoin/.git/
remote: Counting objects: 53782, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 53782 (delta 4), reused 0 (delta 0), pack-reused 53769
Receiving objects: 100% (53782/53782), 48.45 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (38859/38859), done.
From https://github.com/bitcoin/bitcoin
 * [new branch]      0.10       -> 0.10
 * [new branch]      0.8        -> 0.8
 * [new branch]      0.9        -> 0.9
 * [new branch]      master     -> master
--- Building for lucid i386 ---
Stopping target if it is up
Making a new image copy
cp: cannot stat `base-lucid-i386': No such file or directory
./bin/gbuild:21:in `system!': failed to run make-clean-vm --suite lucid --arch i386 (RuntimeError)
	from ./bin/gbuild:57:in `build_one_configuration'
	from ./bin/gbuild:264:in `block (2 levels) in <main>'
	from ./bin/gbuild:259:in `each'
	from ./bin/gbuild:259:in `block in <main>'
	from ./bin/gbuild:257:in `each'
	from ./bin/gbuild:257:in `<main>'
vertoe@debian:~/gitian-builder$ 
```

**Comment by devrandom** [comment]
I apologize, but this has only been tested on Ubuntu, and I don't have the bandwidth to support Debian right now.  I'm happy to accept pull requests...

**Comment by josephbisch** [comment]
Try deleting `base*.qcow2` and recreate them *not* as root.

**Comment by devrandom** [comment]
@vertoe - was LXC=1 in the environment when you did `make-base-vm`?  That flag is required in order to create the raw partition (from the qcow2 one).

**Comment by vertoe** [comment]
Should I poke the bitcoin devs to update the docs? This one is suggesting a Debian Wheezy host: https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md

I can try using an Ubuntu host, that is no problem at all.

I have `export USE_LXC=1` in my `~/.profile`
I also tried creating base-vms with `--lxc`, but experience the same issues.

Creating them *not* as root is not possible, the `make-base-vm` script quotes for `[sudo] password for vertoe:`

**Comment by josephbisch** [comment]
I use the Gitian tools without any issues, but I am on Jessie.

The logs you attached in the gist show you invoking make-base-vm with sudo. Are you sure you tried it without sudo? I know I'm at least able to make them not as root when I don't use sudo.

Here is an excerpt from when I run ls in the my gitian-builder directory, showing that I have an image owned by a non-root user:

```
-rw-r--r--  1 joseph joseph 956M Mar 20 09:22 base-trusty-amd64.qcow2
```

**Comment by devrandom** [comment]
Joseph, are you not using LXC? LXC might need more privileges to unpack
the partition.

On 2015-05-06 12:47 PM, Joseph Bisch wrote:
> I use the Gitian tools without any issues, but I am on Jessie.
> 
> The logs you attached in the gist show you invoking make-base-vm with
> sudo. Are you sure you tried it without sudo? I know I'm at least able
> to make them not as root when I don't use sudo.
> 
> Here is an excerpt from when I run ls in the my gitian-builder
> directory, showing that I have an image owned by a non-root user:
> 
> |-rw-r--r--  1 joseph joseph 956M Mar 20 09:22 base-trusty-amd64.qcow2
> |
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devrandom/gitian-builder/issues/88#issuecomment-99584982>.
> 

-- 
devrandom / Miron

**Comment by vertoe** [comment]
As I said before, running the script asks for superuser privileges, even without typing `sudo`:

```
vertoe@debian:~/gitian-builder$ bin/make-base-vm --arch amd64 --suite precise --lxc
[sudo] password for vertoe: 
2015-05-06 20:38:50,720 INFO    : logging to file: /tmp/tmpbb7bZI
2015-05-06 20:38:50,772 INFO    : Calling hook: preflight_check
2015-05-06 20:38:50,776 INFO    : Calling hook: set_defaults
2015-05-06 20:38:50,781 INFO    : Calling hook: bootstrap
[...]
```

**Comment by josephbisch** [comment]
Ah, sorry. I forgot that the make-base-vm script does prompt you for root permissions even when you don't invoke it with sudo. It also does that when using KVM.

While I don't use LXC right now, because it doesn't seem to work with Jessie, I could have sworn I was able to use it successfully with Debian Wheezy in the past.

**Comment by devrandom** [comment]
@vertoe - when you did `make-base-vm --lxc`, did you get "Extracting partition for lxc" output?  Did the file `base-lucid-amd64` get created?  (notice no .qcow2 extension)

**Comment by vertoe** [comment]
I just tried again with `export LXC=1` and it works.

https://gist.github.com/vertoe/05a5c2100f5ced71dead

Now the file is there. I thought `USE_LXC=1` is enough though.

**Comment by devrandom** [comment]
If you look at the source of make-base-vm, you'll see that --lxc sets
LXC=1.  So not sure why it didn't work for you before.

On 2015-05-06 02:35 PM, vertoe wrote:
> I just tried again with |export LXC=1| and it works.
> 
> https://gist.github.com/vertoe/05a5c2100f5ced71dead
> 
> Now the file is there. I thought |USE_LXC=1| is enough though.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devrandom/gitian-builder/issues/88#issuecomment-99616684>.
> 

-- 
devrandom / Miron

**Comment by vertoe** [comment]
Maybe I forgot to reboot or reload the profile.

It's working as expected now, thanks for your help.

**Comment by Michagogo** [comment]
I've never had to set LXC=1, I just always pass --lxc as an argument to make-base-vm and set USE_LXC=1 when I gbuild. (and prepend LXC_ARCH/LXC_SUITE variables to on-target, where relevant)

**Comment by chryophase** [comment]
For ubuntu16.0.4 (LTS):  ls *.qcow2 results in :    base-xenial-i386.qcow2 , so,
modify your command for .qcow2 to match your build: i.e.  xenial

gitian-builder# bin/make-base-vm --arch i386 --suite xenial --lxc

**Comment by blockchaintrainer** [comment]
Even I am facing the same issue...I am using Ubuntu xenial 64 bit machine.. I have tried all the above solutions but still getting the same error message. I have tried bin/make-base-vm --arch i386 --suite lucid --lxc and gitian-builder# bin/make-base-vm --arch i386 --suite xenial --lxc

**Comment by TTcoinDeveloper** [comment]
Just a general remark: you use "sudo" all the time.... the created files will belong to user "root" and therefore other things will fail later on.

**Comment by blockchaintrainer** [comment]
Thanks @TTcoinDeveloper
