### ISSUE TITLE
"cannot set terminal process group" bug returns.

### ISSUE THREAD

**Issue by Michagogo** [devrandom/gitian-builder#92]
After seeing https://github.com/devrandom/gitian-builder/commit/af56f89a6acffd363c845a489ec163f0d85d30be#diff-9b8ef304d854efc8f914832500619631, I removed the automatic setting of the LXC_EXECUTE environment variable, assuming that gconfig would set it properly. However, that didn't happen and the issue from #63 seems to be back. Are you sure that comparison is in the correct direction?

**Comment by devrandom** [comment]
What version of LXC and OS are you on?

**Comment by Michagogo** [comment]
Ah, I see what happened. I'm on Ubuntu Trusty, the version of the package installed is 1.0.7-0ubuntu0.1.

**Comment by devrandom** [comment]
Should the comparison be with 1.0.0 rather 1.1.0?

**Comment by Michagogo** [comment]
Maybe? I don't know what the version is that makes lxc-start break and
requires lxc-execute. If it's 1.0.0, then compare to that...

**Comment by devrandom** [comment]
OK, changed to 1.0.0 in https://github.com/devrandom/gitian-builder/commit/1913792091dbbbc3f36ee09dbee2664dfed2bf03

**Comment by devrandom** [comment]
Although I don't know for sure what's the correct version.  Depending on feedback from users...
