### ISSUE TITLE
"lxc-start: command not found" when lxc isn't installed and kvm is being used

### ISSUE THREAD

**Issue by josephbisch** [devrandom/gitian-builder#94]
I use kvm. When I try to run gbuild with the lxc package uninstalled (I am running Debian Jessie), I get a bunch of the following outputted in between the useful output:

```
/home/joseph/git/gitian-builder/libexec/gconfig: line 3: lxc-start: command not found
dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
```

This is confusing behavior (because users see mention of lxc, but know that they are using kvm, and start checking their environment variables for USE_LXC, but become confused when they don't have it set). Installing lxc fixes the issue, but users shouldn't need to install lxc to fix this issue.

Note that while this issue doesn't appear to prevent the build from working (I am able to run gbuild to completion and get the expected output), it makes users think something is wrong.

This behavior has been confirmed by other users.

It seems like checking in gconfig for USE_LXC being set and skipping the LXC stuff if it isn't set would fix the issue, but I haven't tried doing that.

CC'ing @droark

**Comment by devrandom** [comment]
I pushed a commit based on USE_LXC.  Please let me know if it fixes.

**Comment by josephbisch** [comment]
I don't see any new commits.

**Comment by devrandom** [comment]
Sorry, pushed.

**Comment by droark** [comment]
Hi. The push seemed to work. I'm seeing some different issues now, though. I figured I'd post here in case they're not worthy of a new issue.

Basically, I can't seem to get the sanity check to work. I'll post the error below. First, here are all the steps I'm following from scratch. Am I doing something wrong? I can post the command line output if you want it.

    sudo apt-get install git apache2 apt-cacher-ng python-vm-builder ruby qemu-utils
    sudo apt-get install qemu-kvm
    sudo bin/make-base-vm --suite trusty  # Seems to install w/o problems
    sudo bin/make-base-vm --suite trusty --arch i386  # Seems to build w/o problems
    PATH=$PATH:$(pwd)/libexec
    make-clean-vm --suite trusty --arch i386
    start-target 32 trusty-i386 &  # Error output below
    on-target ls -la  # Error output below
    stop

Here's the start-target output.

```
[1] 83064
droark@ubuntu:~/Projects/gitian-builder$ /home/droark/Projects/gitian-builder/libexec/start-target: 26: /home/droark/Projects/gitian-builder/libexec/start-target: cannot create var/target.pid: Permission denied
/home/droark/Projects/gitian-builder/libexec/start-target: 25: /home/droark/Projects/gitian-builder/libexec/start-target: cannot create var/target.log: Permission denied
rm: cannot remove ‘var/target.pid’: No such file or directory
```
Here's the on-target output.

```
ssh: connect to host localhost port 2223: Connection refused
[1]+  Exit 1                  start-target 32 trusty-i386
```

I'm pretty sure the "Exit 1" line is actually meant for "start-target" but it doesn't get triggered until you hit Enter. Either way, it looks like something isn't set up properly. Thoughts?

Thanks for all your hard work. :)

**Comment by droark** [comment]
(Perhaps I should just open a new issue....)

Hello. Just double-checked using LXC. Had similar results when trying to run the sanity check.

```
droark@ubuntu:~/Projects/gitian-builder$ make-clean-vm --suite trusty --arch i386
libexec/config-bootstrap-fixup: line 15: target-bin/bootstrap-fixup: Permission denied
droark@ubuntu:~/Projects/gitian-builder$ LXC_ARCH=i386 LXC_SUITE=lucid on-target ls -la
/home/droark/Projects/gitian-builder/libexec/config-lxc: line 13: var/lxc.config: Permission denied
lxc-execute: lxc_execute.c: main: 135 failed to read configuration file
```

**Comment by droark** [comment]
Okay. I just deleted my original posts and will open a new issue. That'll be cleaner.

**Comment by josephbisch** [comment]
So, while I'm not able to test this at this moment, the fix appears to have worked for droark and Alan, who were also experiencing the issue.

So it is probably save to close this issue.

**Comment by devrandom** [comment]
Great.
