### ISSUE TITLE
Sanity check fails

### ISSUE THREAD

**Issue by droark** [devrandom/gitian-builder#95]
(Originally posted [here](https://github.com/devrandom/gitian-builder/issues/94) before I deleted the posts.)

Hello. The LXC push for issue #94 seemed to work. I'm seeing some different issues now, though. I figured I'd post them here in case I'm missing something.

Basically, I can't seem to get the sanity check to work. I'll post the error below. First, here are all the steps I'm following from scratch. Am I doing something wrong? I can post the command line output if you want it. (By the way, this is all done on Ubuntu 15.04, using KVM.)

    sudo apt-get install git apache2 apt-cacher-ng python-vm-builder ruby qemu-utils
    sudo apt-get install qemu-kvm
    sudo bin/make-base-vm --suite trusty  # Seems to install w/o problems
    sudo bin/make-base-vm --suite trusty --arch i386  # Seems to build w/o problems
    PATH=$PATH:$(pwd)/libexec
    make-clean-vm --suite trusty --arch i386
    start-target 32 trusty-i386 &  # Error output below
    on-target ls -la  # Error output below
    stop

Here's the start-target output.

```
[1] 83064
droark@ubuntu:~/Projects/gitian-builder$ /home/droark/Projects/gitian-builder/libexec/start-target: 26: /home/droark/Projects/gitian-builder/libexec/start-target: cannot create var/target.pid: Permission denied
/home/droark/Projects/gitian-builder/libexec/start-target: 25: /home/droark/Projects/gitian-builder/libexec/start-target: cannot create var/target.log: Permission denied
rm: cannot remove ‘var/target.pid’: No such file or directory
```
Here's the on-target output.

```
ssh: connect to host localhost port 2223: Connection refused
[1]+  Exit 1                  start-target 32 trusty-i386
```

I'm pretty sure the "Exit 1" line is actually meant for "start-target" but it doesn't get triggered until you hit Enter. Either way, it looks like something isn't set up properly. Thoughts? I double-checked using LXC. Had similar results when trying to run the sanity check.

```
droark@ubuntu:~/Projects/gitian-builder$ make-clean-vm --suite trusty --arch i386
libexec/config-bootstrap-fixup: line 15: target-bin/bootstrap-fixup: Permission denied
droark@ubuntu:~/Projects/gitian-builder$ LXC_ARCH=i386 LXC_SUITE=lucid on-target ls -la
/home/droark/Projects/gitian-builder/libexec/config-lxc: line 13: var/lxc.config: Permission denied
lxc-execute: lxc_execute.c: main: 135 failed to read configuration file
```
Thanks for all your hard work. :)

**Comment by devrandom** [comment]
Could you check the ownership of the `var` directory?  maybe it's owned by root because of something you tried earlier?

**Comment by droark** [comment]
Hello. /var is indeed owned by root. Does Ubuntu do that by default? I thought it did. Anyway, I'll look into that and see about switching ownership to my account if it's appropriate. I'll report back with my results.

Thanks.

**Comment by devrandom** [comment]
Look at ./var , not the system one.

**Comment by droark** [comment]
Ahhh, sorry. Yes, it is owned by root. I'll fix that and report back.

**Comment by droark** [comment]
Hello. Changing ./var ownership did fix that problem. I had some problems after that but it turned out that I hadn't activated hypervisor applications for my VM. (I run Ubuntu in a VM.) Once I did that, the sanity check passed for KVM. LXC is still failing, unfortunately. I'm getting the following error when exporting USE_LXC=1. ./var and the target are owned by me, and the base is owned by root.

```
droark@ubuntu:~/Projects/gitian-builder$ make-clean-vm --suite trusty --arch i386
libexec/config-bootstrap-fixup: line 15: target-bin/bootstrap-fixup: Permission denied
droark@ubuntu:~/Projects/gitian-builder$ LXC_ARCH=i386 LXC_SUITE=trusty on-target ls -la
lxc-execute: conf.c: instantiate_veth: 2660 failed to attach 'vethBQD1JJ' to the bridge 'br0': Operation not permitted
lxc-execute: conf.c: lxc_create_network: 2943 failed to create netdev
lxc-execute: start.c: lxc_spawn: 914 failed to create the network
lxc-execute: start.c: __lxc_start: 1164 failed to spawn 'gitian'
```

Thanks for the assistance.

**Comment by devrandom** [comment]
Glad you are making progress.  Let me know what is the symptom for LXC.

**Comment by droark** [comment]
The basic symptoms are the ones seen [here.](https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1451232) It looks like the updated bug report [here](https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1452601) has been open for a month. It probably wouldn't hurt to get some people to sign up and report that it's affecting them.

**Comment by devrandom** [comment]
Got it.

**Comment by josephbisch** [comment]
I understand why you closed this, but I just wanted to post so that people know the following.

I reproduced the issue using an Ubuntu 15.04 chroot on my Debian Jessie system. I encountered it while running `make-clean-vm --suite trusty --arch amd64`. So I will post on Launchpad about it at the bug report links that droark posted.

**Comment by devrandom** [comment]
Just to make sure, there's no workaround that we can implement in gitian, right?

**Comment by josephbisch** [comment]
Doesn't seem to be any.

**Comment by phantanthanh1996** [comment]
Hi, I have same problem when use gitian, gitian-builder/libexec/start-target: cannot create var/target.pid: Permission denied. So how to fix it, pls help me!

**Comment by devrandom** [comment]
This seems to be unrelated to the original issue here.  Could you check if `var/target.pid` exists and the owner of it?  If you still have a problem, please open another issue.
